#!/bin/bash
# SubagentStop hook — automatic reporting of a Claude Code run of a PLATFORM
# agent back to the platform (HIER-P1C item 4a), so the agent's execution,
# trust and model statistics see the run exactly as they see a platform
# execution (platform.record_agent_execution → Ai::AgentExecution).
#
# What it does, in order:
#   1. Reads the SubagentStop payload on stdin (session_id, agent_id,
#      agent_type, transcript_path). agent_type is the subagent name — for a
#      platform agent that is its slug.
#   2. Skips everything that is not a platform agent: the name must match a
#      GENERATED skeleton (.claude/agents/powernode/<slug>.md, or the local
#      export under powernode-local/) whose frontmatter `name:` is that slug.
#      general-purpose, Explore, Plan, hand-authored agents → no call.
#   3. Parses the subagent's own transcript
#      (<transcript dir>/<session_id>/subagents/agent-<agent_id>.jsonl): the
#      model that served, token usage (a streamed message appears twice under
#      one message.id — counted once), wall-clock duration, the outcome, and a
#      ≤500-char task digest. If the subagent already self-reported (the
#      skeleton body's final step), its run_key is reused so the platform sees
#      ONE row; otherwise run_key = "<session_id>:<agent_id>".
#   4. POSTs ONE JSON-RPC tools/call to the local MCP endpoint the session
#      already uses (the 127.0.0.1:18443 proxy by default — read from
#      ~/.claude.json's `powernode` entry, or POWERNODE_MCP_URL). Fire-and-
#      forget: the request runs in the background with a 5 s budget, the hook
#      itself never blocks, never exits non-zero, and never logs a body.
#
# Test seams (server/spec/hooks/subagent_report_spec.rb):
#   POWERNODE_MCP_URL            the endpoint (a throwaway listener in the spec)
#   SUBAGENT_REPORT_FOREGROUND=1 wait for the request instead of backgrounding it
#   CLAUDE_PROJECT_DIR           where .claude/agents/ lives (defaults to the payload's cwd)
set -uo pipefail

payload="$(cat 2>/dev/null || true)"
[[ -n "$payload" ]] || exit 0
command -v jq >/dev/null 2>&1 || exit 0
command -v curl >/dev/null 2>&1 || exit 0

field() { jq -r "$1 // empty" <<<"$payload" 2>/dev/null; }
agent_type="$(field '.agent_type')"
session_id="$(field '.session_id')"
agent_id="$(field '.agent_id')"
transcript_path="$(field '.transcript_path')"
agent_transcript="$(field '.agent_transcript_path')"
[[ -n "$agent_type" && -n "$session_id" && -n "$agent_id" ]] || exit 0

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(field '.cwd')}"
[[ -n "$PROJECT_DIR" ]] || exit 0

# --- 2. platform agent? ------------------------------------------------------
GENERATED_MARKER='generated by claude:sync_agents'
skeleton=""
for dir in powernode powernode-local; do
  candidate="$PROJECT_DIR/.claude/agents/$dir/$agent_type.md"
  [[ -f "$candidate" ]] || continue
  grep -q "$GENERATED_MARKER" "$candidate" 2>/dev/null || continue
  # frontmatter `name:` (first block between the --- fences) must be the slug
  name="$(awk 'NR==1{ if ($0!="---") exit; next } $0=="---"{exit} /^name:[ \t]*/{sub(/^name:[ \t]*/,""); print; exit}' "$candidate" 2>/dev/null)"
  [[ "$name" == "$agent_type" ]] || continue
  skeleton="$candidate"
  break
done
[[ -n "$skeleton" ]] || exit 0

# --- 3. the subagent's transcript -------------------------------------------
if [[ -z "$agent_transcript" || ! -f "$agent_transcript" ]]; then
  [[ -n "$transcript_path" ]] || exit 0
  agent_transcript="$(dirname "$transcript_path")/$session_id/subagents/agent-$agent_id.jsonl"
fi
[[ -f "$agent_transcript" ]] || exit 0

args="$(jq -s --arg slug "$agent_type" --arg default_run_key "$session_id:$agent_id" '
  [ .[] | select(type == "object") ] as $rows
  | ($rows | map(select(.type == "assistant" and (.message | type) == "object"))) as $assistants
  # a streamed message is written once as a partial and once final under the
  # same message.id: keep the LAST record per id, and any record without an id
  | (($assistants | map(select(.message.id != null)) | group_by(.message.id) | map(last))
     + ($assistants | map(select(.message.id == null)))) as $messages
  | ($messages | map(.message.usage // {})) as $usages
  | ($rows | map(.timestamp // empty) | map(select(. != ""))) as $timestamps
  | ($assistants | last) as $last
  | def epoch: sub("\\.[0-9]+Z$"; "Z") | fromdateiso8601;
  {
    agent_slug: $slug,
    model: (($assistants | map(.message.model // empty) | last) // "unknown"),
    outcome: (if (($last // {}) | .isApiErrorMessage // false) == true then "failed" else "completed" end),
    duration_ms: (if ($timestamps | length) >= 2
                  then ((($timestamps | last | epoch) - ($timestamps | first | epoch)) * 1000)
                  else 0 end),
    # TOKEN CONVENTION: `input` is the FULL billed input footprint —
    # input_tokens + cache_read + cache_creation — because that is what the run
    # actually consumed; a long CC session reads a large cache, so this number
    # is not comparable to a platform execution that ran without one. Pinned by
    # server/spec/hooks/subagent_report_spec.rb.
    tokens: {
      input:  ($usages | map((.input_tokens // 0) + (.cache_read_input_tokens // 0) + (.cache_creation_input_tokens // 0)) | add // 0),
      output: ($usages | map(.output_tokens // 0) | add // 0)
    },
    task_digest: (($rows | map(select(.type == "user")) | first | .message.content
                   | if type == "string" then .
                     elif type == "array" then (map(select(.type == "text") | .text // "") | join(" "))
                     else "" end
                   | .[0:500]) // ""),
    run_key: (($assistants
               | map(.message.content // [] | if type == "array" then .[] else empty end
                     | select(.type == "tool_use" and ((.name // "") | endswith("platform_record_agent_execution")))
                     | .input.run_key // empty)
               | last) // $default_run_key)
  }' "$agent_transcript" 2>/dev/null)"
[[ -n "$args" ]] || exit 0

body="$(jq -cn --argjson args "$args" \
  '{jsonrpc: "2.0", id: 1, method: "tools/call", params: {name: "platform.record_agent_execution", arguments: $args}}' 2>/dev/null)"
[[ -n "$body" ]] || exit 0

# --- 4. the endpoint ---------------------------------------------------------
url="${POWERNODE_MCP_URL:-}"
auth_args=()
if [[ -z "$url" && -f "$HOME/.claude.json" ]]; then
  url="$(jq -r '.mcpServers.powernode.url // empty' "$HOME/.claude.json" 2>/dev/null)"
  auth="$(jq -r '.mcpServers.powernode.headers.Authorization // empty' "$HOME/.claude.json" 2>/dev/null)"
  [[ -n "$auth" ]] && auth_args=(-H "Authorization: $auth")
fi
[[ -n "$url" ]] || url="http://127.0.0.1:18443/mcp"

send() {
  curl -sS -m 5 --connect-timeout 2 -o /dev/null -X POST "$url" \
    -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' \
    "${auth_args[@]}" --data-binary "$body" >/dev/null 2>&1
}

if [[ "${SUBAGENT_REPORT_FOREGROUND:-0}" == "1" ]]; then
  send
else
  ( send ) >/dev/null 2>&1 &
fi

echo "⟳ Reported platform agent run ($agent_type) to the platform statistics" >&2
exit 0
