# frozen_string_literal: true

namespace :system do
  namespace :skills do
    desc "Generate system extension skill executor catalog from descriptor() methods"
    task generate_catalog: :environment do
      skills_dir = Rails.root.join(
        "..",
        "extensions/system/server/app/services/system/ai/skills"
      ).cleanpath

      unless skills_dir.directory?
        puts "Skills directory not found: #{skills_dir}"
        puts "(The system extension may be disabled or unmounted.)"
        exit 1
      end

      executor_paths = Dir[skills_dir.join("*_executor.rb")].sort
      executors      = []
      load_failures  = []

      executor_paths.each do |path|
        class_basename = File.basename(path, ".rb").camelize
        begin
          klass = "System::Ai::Skills::#{class_basename}".constantize
        rescue NameError => e
          load_failures << { path: path, error: "#{e.class}: #{e.message}" }
          next
        end

        # Skip the abstract base class — it intentionally raises from
        # `.descriptor` (it has no skill_descriptor of its own) and is a
        # superclass, not a real skill. Matching `*_executor.rb` sweeps it in.
        next if klass == ::System::Ai::Skills::BaseSkillExecutor

        unless klass.respond_to?(:descriptor)
          load_failures << { path: path, error: "no .descriptor class method" }
          next
        end

        begin
          descriptor = klass.descriptor
        rescue StandardError, NotImplementedError => e
          load_failures << { path: path, error: "descriptor raised #{e.class}: #{e.message}" }
          next
        end

        executors << descriptor.merge(
          executor_class: klass.name,
          source_path: path.sub("#{Rails.root.join('..').cleanpath}/", "")
        )
      end

      by_category = executors.group_by { |e| (e[:category] || "uncategorized").to_s }.sort

      lines = []
      lines << "# Skill Executor Catalog — System Extension (Auto-Generated)"
      lines << ""
      lines << "> Auto-generated by `rails system:skills:generate_catalog` on #{Time.current.strftime('%Y-%m-%d %H:%M UTC')}."
      lines << "> Source: `descriptor()` class methods on `extensions/system/server/app/services/system/ai/skills/*_executor.rb`."
      lines << "> Do NOT edit by hand — re-run the rake task instead."
      lines << ""
      lines << "**#{executors.size} executors** across **#{by_category.size} categories**."
      if load_failures.any?
        lines << ""
        lines << "Skipped #{load_failures.size} executor file(s) that didn't load or expose a descriptor — see end of file for details."
      end
      lines << ""
      lines << "For architecture context (agent bindings, plan vs. execute pattern, invocation surfaces), see [SKILL_EXECUTORS.md](./SKILL_EXECUTORS.md)."
      lines << ""
      lines << "---"
      lines << ""

      lines << "## Table of Contents"
      lines << ""
      by_category.each do |cat, execs|
        lines << "### #{cat.titleize} (#{execs.size})"
        lines << ""
        execs.sort_by { |e| e[:name].to_s }.each do |e|
          anchor = e[:name].to_s.tr("_", "-")
          desc   = e[:description].to_s.lines.first.to_s.chomp
          lines << "- [`#{e[:name]}`](##{anchor}) — #{desc}"
        end
        lines << ""
      end

      lines << "---"
      lines << ""

      by_category.each do |cat, execs|
        lines << "## #{cat.titleize}"
        lines << ""
        execs.sort_by { |e| e[:name].to_s }.each do |e|
          lines << "### `#{e[:name]}`"
          lines << ""
          lines << e[:description].to_s
          lines << ""
          lines << "- **Class:** `#{e[:executor_class]}`"
          lines << "- **Source:** `#{e[:source_path]}`"
          lines << "- **Category:** #{e[:category]}" if e[:category]
          lines << ""

          if e[:inputs].is_a?(Hash) && e[:inputs].any?
            lines << "**Inputs**"
            lines << ""
            lines << "| Field | Type | Required | Description |"
            lines << "|-------|------|----------|-------------|"
            e[:inputs].each do |field, spec|
              spec     = {} unless spec.is_a?(Hash)
              type     = spec[:type] || spec["type"] || "?"
              required = (spec[:required] || spec["required"]) ? "Yes" : "No"
              desc     = spec[:description] || spec["description"] || "-"
              lines << "| `#{field}` | #{type} | #{required} | #{desc} |"
            end
            lines << ""
          end

          if e[:outputs].is_a?(Hash) && e[:outputs].any?
            lines << "**Outputs**"
            lines << ""
            e[:outputs].each do |field, type|
              type_repr =
                if type.is_a?(Array)
                  "array<#{type.first}>"
                else
                  type.to_s
                end
              lines << "- `#{field}`: #{type_repr}"
            end
            lines << ""
          end
        end
        lines << "---"
        lines << ""
      end

      if load_failures.any?
        lines << "## Skipped executors"
        lines << ""
        lines << "These executor files did not load or did not expose a `descriptor()` class method."
        lines << "Either fix the executor or remove the file."
        lines << ""
        load_failures.each do |f|
          rel = f[:path].sub("#{Rails.root.join('..').cleanpath}/", "")
          lines << "- `#{rel}` — #{f[:error]}"
        end
        lines << ""
      end

      output_path = Rails.root.join(
        "..",
        "extensions/system/docs/SKILL_EXECUTOR_CATALOG.md"
      ).cleanpath
      FileUtils.mkdir_p(File.dirname(output_path))
      File.write(output_path, lines.join("\n"))

      puts "Generated catalog for #{executors.size} executors across #{by_category.size} categories"
      puts "Output: #{output_path}"
      puts "Skipped: #{load_failures.size} executor file(s)" if load_failures.any?
    end
  end
end
