# frozen_string_literal: true

require "rails_helper"
require_relative "../../../app/services/devops/sbom_generator"

# Worker-side best-effort CycloneDX SBOM generator (Loop Engineering Parity FU6),
# composed into the land security-scan job ALONGSIDE the secret scanner, Brakeman,
# and the dependency-CVE scanner. It reads the standard dependency lockfiles in a
# checked-out repo and emits a CycloneDX 1.5 JSON inventory of name/version/purl
# components. PURE METADATA: it never blocks or fails the land. The file reader is
# injected with canned manifest content — no filesystem is touched in these specs.
RSpec.describe Devops::SbomGenerator do
  # Maps a relative manifest path to its canned content; any other path → nil
  # (manifest absent), exactly like the File-backed default reader.
  def reader_for(files)
    ->(relative) { files[relative] }
  end

  let(:gemfile_lock) do
    <<~LOCK
      GEM
        remote: https://rubygems.org/
        specs:
          nokogiri (1.13.9)
            racc (~> 1.4)
          rack (2.2.4)

      PLATFORMS
        ruby

      DEPENDENCIES
        nokogiri
        rack

      BUNDLED WITH
         2.3.7
    LOCK
  end

  # package-lock v3 (lockfileVersion 3, "packages" map). Includes a scoped name and
  # a `resolved` URL carrying a token to prove the SBOM never embeds it.
  let(:package_lock_v3) do
    {
      "name" => "app",
      "lockfileVersion" => 3,
      "packages" => {
        "" => { "name" => "app", "version" => "1.0.0" },
        "node_modules/lodash" => {
          "version" => "4.17.21",
          "resolved" => "https://x-token-SECRET@registry.example/lodash/-/lodash-4.17.21.tgz",
          "integrity" => "sha512-DEADBEEF",
          "license" => "MIT"
        },
        "node_modules/@babel/core" => { "version" => "7.20.0" }
      }
    }.to_json
  end

  let(:package_lock_v1) do
    {
      "name" => "app", "lockfileVersion" => 1,
      "dependencies" => {
        "express" => {
          "version" => "4.18.2",
          "dependencies" => { "accepts" => { "version" => "1.3.8" } }
        }
      }
    }.to_json
  end

  let(:yarn_lock) do
    <<~LOCK
      # THIS IS AN AUTOGENERATED FILE. yarn lockfile v1
      lodash@^4.17.0:
        version "4.17.21"
        resolved "https://x-token-SECRET@registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

      "@babel/core@^7.0.0", "@babel/core@^7.1.0":
        version "7.20.0"
    LOCK
  end

  let(:requirements_txt) do
    <<~REQ
      flask==1.1.2
      requests[security]==2.25.1  # extras + comment
      -r dev-requirements.txt
      --index-url https://user:pass@pypi.example/simple
      git+https://x-token-SECRET@github.com/acme/widget.git#egg=widget
      range-only>=1.0
    REQ
  end

  let(:poetry_lock) do
    <<~LOCK
      [[package]]
      name = "flask"
      version = "2.0.1"
      description = "A simple framework"

      [package.dependencies]
      werkzeug = ">=2.0"

      [[package]]
      name = "requests"
      version = "2.26.0"
    LOCK
  end

  describe ".generate" do
    it "emits a CycloneDX 1.5 JSON document with a generator tool and the repo name" do
      result = described_class.generate("/ws", reader: reader_for("Gemfile.lock" => gemfile_lock), component_name: "acme/widget")
      doc = result[:document]

      expect(result[:format]).to eq("CycloneDX")
      expect(result[:spec_version]).to eq("1.5")
      expect(result[:generated]).to be(true)
      expect(doc["bomFormat"]).to eq("CycloneDX")
      expect(doc["specVersion"]).to eq("1.5")
      expect(doc["version"]).to eq(1)
      expect(doc.dig("metadata", "tools")).to be_an(Array).and be_present
      expect(doc.dig("metadata", "component", "name")).to eq("acme/widget")
    end

    it "inventories top-level Gemfile.lock gems as gem-purl library components" do
      result = described_class.generate("/ws", reader: reader_for("Gemfile.lock" => gemfile_lock))
      components = result[:document]["components"]
      names = components.map { |c| c["name"] }

      expect(names).to include("nokogiri", "rack")
      # 6-space sub-dependencies (racc) are NOT top-level specs → excluded.
      expect(names).not_to include("racc")

      nokogiri = components.find { |c| c["name"] == "nokogiri" }
      expect(nokogiri["type"]).to eq("library")
      expect(nokogiri["version"]).to eq("1.13.9")
      expect(nokogiri["purl"]).to eq("pkg:gem/nokogiri@1.13.9")
      expect(nokogiri["bom-ref"]).to eq("pkg:gem/nokogiri@1.13.9")
    end

    it "parses npm package-lock v3 packages, skips the root project, and encodes scoped names" do
      result = described_class.generate("/ws", reader: reader_for("package-lock.json" => package_lock_v3))
      components = result[:document]["components"]
      names = components.map { |c| c["name"] }

      expect(names).to include("lodash", "@babel/core")
      expect(names).not_to include("app") # the "" root entry is the project, not a dependency

      babel = components.find { |c| c["name"] == "@babel/core" }
      expect(babel["purl"]).to eq("pkg:npm/%40babel/core@7.20.0")
    end

    it "parses npm package-lock v1 dependencies (nested) as a fallback shape" do
      result = described_class.generate("/ws", reader: reader_for("package-lock.json" => package_lock_v1))
      names = result[:document]["components"].map { |c| c["name"] }
      expect(names).to include("express", "accepts")
    end

    it "parses yarn.lock classic v1 entries" do
      result = described_class.generate("/ws", reader: reader_for("yarn.lock" => yarn_lock))
      components = result[:document]["components"]
      names = components.map { |c| c["name"] }

      expect(names).to include("lodash", "@babel/core")
      expect(components.find { |c| c["name"] == "lodash" }["version"]).to eq("4.17.21")
    end

    it "parses yarn.lock Berry (v2+) 'version: x' entries and ignores the __metadata block" do
      berry = <<~LOCK
        # This file is generated by running "yarn install"

        __metadata:
          version: 8
          cacheKey: 10

        "lodash@npm:^4.17.0":
          version: 4.17.21
          resolution: "lodash@npm:4.17.21"

        "@babel/core@npm:^7.0.0":
          version: 7.20.0
      LOCK
      result = described_class.generate("/ws", reader: reader_for("yarn.lock" => berry))
      names = result[:document]["components"].map { |c| c["name"] }

      expect(names).to include("lodash", "@babel/core")
      expect(names).not_to include("__metadata") # yarn metadata is not a package
      expect(result[:document]["components"].find { |c| c["name"] == "lodash" }["version"]).to eq("4.17.21")
    end

    it "parses requirements.txt == pins only and ignores options, URLs, and ranges" do
      result = described_class.generate("/ws", reader: reader_for("requirements.txt" => requirements_txt))
      components = result[:document]["components"]
      names = components.map { |c| c["name"] }

      expect(names).to include("flask", "requests")
      expect(names).not_to include("range-only") # no exact == pin → omitted
      expect(names).not_to include("dev-requirements", "widget") # -r / VCS URL lines skipped

      flask = components.find { |c| c["name"] == "flask" }
      expect(flask["purl"]).to eq("pkg:pypi/flask@1.1.2")
    end

    it "parses PEP 440 arbitrary-equality (===) requirements pins" do
      result = described_class.generate("/ws", reader: reader_for("requirements.txt" => "django===4.2.1\n"))
      component = result[:document]["components"].first
      expect(component["name"]).to eq("django")
      expect(component["version"]).to eq("4.2.1")
    end

    it "parses poetry.lock [[package]] blocks and ignores dependency constraint tables" do
      result = described_class.generate("/ws", reader: reader_for("poetry.lock" => poetry_lock))
      names = result[:document]["components"].map { |c| c["name"] }

      expect(names).to include("flask", "requests")
      expect(names).not_to include("werkzeug") # a [package.dependencies] constraint, not a package
    end

    it "dedupes a package present in more than one manifest by purl" do
      result = described_class.generate(
        "/ws",
        reader: reader_for("package-lock.json" => package_lock_v3, "yarn.lock" => yarn_lock)
      )
      lodash = result[:document]["components"].select { |c| c["name"] == "lodash" }
      expect(lodash.size).to eq(1)
    end

    it "NEVER embeds resolved-URL tokens, integrity hashes, or credentials in the SBOM" do
      result = described_class.generate(
        "/ws",
        reader: reader_for(
          "package-lock.json" => package_lock_v3,
          "yarn.lock" => yarn_lock,
          "requirements.txt" => requirements_txt
        )
      )
      json = result.to_json
      expect(json).not_to include("x-token-SECRET")
      expect(json).not_to include("user:pass")
      expect(json).not_to include("DEADBEEF") # integrity hash must not leak either
    end

    it "skips an npm v1 dependency whose version is a credentialed git URL (never leaks the token)" do
      v1_git = {
        "name" => "app", "lockfileVersion" => 1,
        "dependencies" => {
          "foo" => { "version" => "git+https://x-access-token:ghp_ABC123DEF456@github.com/org/foo.git#deadbeef" },
          "lodash" => { "version" => "4.17.21" }
        }
      }.to_json
      result = described_class.generate("/ws", reader: reader_for("package-lock.json" => v1_git))
      names = result[:document]["components"].map { |c| c["name"] }

      expect(names).to include("lodash") # the clean dependency is still inventoried
      expect(names).not_to include("foo") # the git-URL-versioned dependency is skipped
      expect(result.to_json).not_to include("ghp_ABC123DEF456")
      expect(result.to_json).not_to include("x-access-token")
    end

    it "skips a yarn git/url dependency whose descriptor embeds a credential (never leaks it)" do
      yarn_git = <<~LOCK
        # yarn lockfile v1
        "foo@git+https://user:tok3nSECRET@github.com/org/foo.git":
          version "1.0.0"

        lodash@^4.17.0:
          version "4.17.21"
      LOCK
      result = described_class.generate("/ws", reader: reader_for("yarn.lock" => yarn_git))
      names = result[:document]["components"].map { |c| c["name"] }

      expect(names).to include("lodash")
      expect(names).not_to include(a_string_matching(/foo@git/))
      expect(result.to_json).not_to include("tok3nSECRET")
    end

    it "skips any component whose name or version is not a simple ecosystem identifier" do
      # A maliciously crafted requirements-style pair where the 'version' is a URL
      # must never reach the SBOM as a component.
      reader = lambda do |relative|
        { "requirements.txt" => "good==1.0.0\n" }[relative]
      end
      result = described_class.generate("/ws", reader: reader)
      names = result[:document]["components"].map { |c| c["name"] }
      expect(names).to eq([ "good" ])
    end

    it "returns a valid, empty inventory (generated, 0 components) when no manifests are present" do
      result = described_class.generate("/ws", reader: reader_for({}))
      expect(result[:generated]).to be(true)
      expect(result[:component_count]).to eq(0)
      expect(result[:document]["components"]).to eq([])
      expect(result[:document]["bomFormat"]).to eq("CycloneDX")
    end

    it "skips a single unreadable manifest but still inventories the others (best-effort)" do
      reader = lambda do |relative|
        raise "io error" if relative == "Gemfile.lock"

        { "requirements.txt" => "flask==1.1.2\n" }[relative]
      end
      result = described_class.generate("/ws", reader: reader)
      names = result[:document]["components"].map { |c| c["name"] }
      expect(result[:generated]).to be(true)
      expect(names).to eq([ "flask" ])
    end

    it "attaches a degraded (non-raising) result if component collection itself fails" do
      allow(described_class).to receive(:collect_components).and_raise(StandardError.new("boom"))
      result = described_class.generate("/ws", reader: reader_for("Gemfile.lock" => gemfile_lock))

      expect(result[:generated]).to be(false)
      expect(result[:component_count]).to eq(0)
      expect(result[:document]).to be_a(Hash) # still a valid, empty CycloneDX doc
      expect(result[:document]["components"]).to eq([])
    end

    it "caps the component count and flags truncation for a pathologically large manifest" do
      stub_const("#{described_class}::MAX_COMPONENTS", 2)
      lock = +"GEM\n  specs:\n"
      5.times { |i| lock << "    gem#{i} (1.0.#{i})\n" }
      result = described_class.generate("/ws", reader: reader_for("Gemfile.lock" => lock))

      expect(result[:truncated]).to be(true)
      expect(result[:component_count]).to eq(2)
      expect(result[:document]["components"].size).to eq(2)
    end

    it "uses the File-backed default reader when none is injected (no crash on a missing dir)" do
      expect { described_class.generate("/nonexistent/workspace/xyz") }.not_to raise_error
      result = described_class.generate("/nonexistent/workspace/xyz")
      expect(result[:generated]).to be(true)
      expect(result[:component_count]).to eq(0)
    end
  end
end
