# frozen_string_literal: true

require "spec_helper"
require "json"
require "open3"
require "socket"
require "tmpdir"
require "fileutils"

# HIER-P1C item 4(a): .claude/hooks/subagent-report.sh on the SubagentStop
# hook event. Shell-level fixture spec — no Rails: a saved SubagentStop payload
# plus a saved subagent transcript go in, and the JSON-RPC `tools/call` body
# the hook POSTs to the local MCP proxy comes out (captured by a throwaway
# HTTP listener standing in for 127.0.0.1:18443). A subagent that is not a
# platform agent (no generated skeleton by that name) produces NO call.
RSpec.describe ".claude/hooks/subagent-report.sh" do
  let(:repo_root) { File.expand_path("../../..", __dir__) }
  let(:hook) { File.join(repo_root, ".claude", "hooks", "subagent-report.sh") }

  let(:project_dir) { Dir.mktmpdir("subagent-report-project") }
  let(:transcripts_dir) { Dir.mktmpdir("subagent-report-transcripts") }
  let(:session_id) { "3d951ce2-d621-4a98-acca-c6f3cbac5e7e" }
  let(:agent_id) { "a97d9f756851ca1db" }

  after do
    FileUtils.remove_entry(project_dir) if File.exist?(project_dir)
    FileUtils.remove_entry(transcripts_dir) if File.exist?(transcripts_dir)
  end

  # A committed canonical skeleton, as Ai::ClaudeExport::AgentSkeletonSync renders it.
  def write_skeleton(slug, dir: "powernode")
    path = File.join(project_dir, ".claude", "agents", dir)
    FileUtils.mkdir_p(path)
    File.write(File.join(path, "#{slug}.md"), <<~MD)
      ---
      name: #{slug}
      description: Use this agent when the task involves CVE intake.
      model: opus
      ---

      This is the Claude Code counterpart of the Powernode platform agent "CVE Responder" (slug `#{slug}`).

      <!-- generated by claude:sync_agents — do not edit; regenerate instead -->
    MD
  end

  # The subagent's own transcript, in the location Claude Code writes it:
  # <transcript dir>/<session id>/subagents/agent-<agent id>.jsonl. Record
  # shapes mirror a real transcript: a streamed assistant message appears
  # TWICE with the same message.id (a partial, then the final usage).
  def write_transcript(entries)
    dir = File.join(transcripts_dir, session_id, "subagents")
    FileUtils.mkdir_p(dir)
    File.write(File.join(dir, "agent-#{agent_id}.jsonl"), entries.map(&:to_json).join("\n") + "\n")
  end

  def assistant(model:, id:, output_tokens:, timestamp:, stop_reason: "end_turn", input_tokens: 2, cache_read: 100, content: [ { "type" => "text", "text" => "ok" } ])
    { "type" => "assistant", "agentId" => agent_id, "sessionId" => session_id, "timestamp" => timestamp,
      "message" => { "id" => id, "model" => model, "role" => "assistant", "stop_reason" => stop_reason, "content" => content,
                     "usage" => { "input_tokens" => input_tokens, "cache_read_input_tokens" => cache_read,
                                  "cache_creation_input_tokens" => 0, "output_tokens" => output_tokens } } }
  end

  def user_prompt(text, timestamp:)
    { "type" => "user", "agentId" => agent_id, "sessionId" => session_id, "timestamp" => timestamp,
      "message" => { "role" => "user", "content" => text } }
  end

  def default_transcript
    [
      user_prompt("triage the new critical CVE for the fleet\nsecret=do-not-send", timestamp: "2026-09-03T20:00:00.000Z"),
      assistant(model: "claude-opus-5", id: "msg_1", output_tokens: 3, timestamp: "2026-09-03T20:00:05.000Z", stop_reason: nil),
      assistant(model: "claude-opus-5", id: "msg_1", output_tokens: 300, timestamp: "2026-09-03T20:00:09.000Z"),
      assistant(model: "claude-opus-5", id: "msg_2", output_tokens: 120, timestamp: "2026-09-03T20:00:42.000Z")
    ]
  end

  def payload(agent_type:)
    { "session_id" => session_id, "transcript_path" => File.join(transcripts_dir, "#{session_id}.jsonl"),
      "cwd" => project_dir, "hook_event_name" => "SubagentStop", "stop_hook_active" => false,
      "agent_id" => agent_id, "agent_type" => agent_type }.to_json
  end

  # Throwaway HTTP listener standing in for the local MCP proxy: captures one
  # request body, answers 200. Returns [url, requests] where requests fills in.
  def start_listener
    server = TCPServer.new("127.0.0.1", 0)
    port = server.addr[1]
    requests = []
    thread = Thread.new do
      loop do
        client = server.accept
        request_line = client.gets
        headers = {}
        while (line = client.gets) && line != "\r\n"
          key, value = line.split(":", 2)
          headers[key.strip.downcase] = value.strip
        end
        body = client.read(headers["content-length"].to_i)
        requests << { line: request_line, headers: headers, body: body }
        client.write("HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 2\r\nConnection: close\r\n\r\n{}")
        client.close
      end
    rescue IOError, Errno::EBADF
      nil
    end
    [ "http://127.0.0.1:#{port}/mcp", requests, server, thread ]
  end

  def run_hook(stdin, url:)
    env = {
      "CLAUDE_PROJECT_DIR" => project_dir,
      "POWERNODE_MCP_URL" => url,
      "SUBAGENT_REPORT_FOREGROUND" => "1"
    }
    Open3.capture3(env, "bash", hook, stdin_data: stdin)
  end

  it "is executable and wired to the SubagentStop event in .claude/settings.json" do
    expect(File.executable?(hook)).to be(true), "#{hook} must exist and be executable"
    settings = JSON.parse(File.read(File.join(repo_root, ".claude", "settings.json")))
    commands = settings.dig("hooks", "SubagentStop").to_a.flat_map { |group| group["hooks"].to_a }.map { |h| h["command"] }
    expect(commands.join(" ")).to include("subagent-report.sh")
    expect(settings.dig("hooks", "SubagentStop").to_a.flat_map { |g| g["hooks"] }.find { |h| h["command"].include?("subagent-report.sh") }["timeout"]).to be <= 5
  end

  context "a platform agent subagent (a generated skeleton exists under that name)" do
    before { write_skeleton("cve-responder") }

    it "POSTs one tools/call for platform.record_agent_execution built from the transcript" do
      write_transcript(default_transcript)
      url, requests, server, thread = start_listener

      _out, err, status = run_hook(payload(agent_type: "cve-responder"), url: url)

      expect(status.exitstatus).to eq(0), err
      expect(requests.size).to eq(1)
      request = requests.first
      expect(request[:line]).to start_with("POST /mcp ")
      expect(request[:headers]["content-type"]).to include("application/json")

      rpc = JSON.parse(request[:body])
      expect(rpc["jsonrpc"]).to eq("2.0")
      expect(rpc["method"]).to eq("tools/call")
      expect(rpc.dig("params", "name")).to eq("platform.record_agent_execution")

      args = rpc.dig("params", "arguments")
      expect(args["agent_slug"]).to eq("cve-responder")
      expect(args["model"]).to eq("claude-opus-5")
      expect(args["outcome"]).to eq("completed")
      expect(args["run_key"]).to eq("#{session_id}:#{agent_id}")
      # streamed duplicate (msg_1 partial + final) counted ONCE: 300 + 120
      expect(args["tokens"]).to eq("input" => 204, "output" => 420)
      expect(args["duration_ms"]).to eq(42_000)
      expect(args["task_digest"]).to start_with("triage the new critical CVE")
      expect(args["task_digest"].length).to be <= 500
    ensure
      server&.close
      thread&.kill
    end

    it "reuses a self-report's run_key found in the transcript so the platform sees one row" do
      entries = default_transcript
      entries.insert(3, assistant(
        model: "claude-opus-5", id: "msg_tool", output_tokens: 10, timestamp: "2026-09-03T20:00:20.000Z", stop_reason: "tool_use",
        content: [ { "type" => "tool_use", "id" => "toolu_1", "name" => "mcp__powernode__platform_record_agent_execution",
                     "input" => { "agent_slug" => "cve-responder", "run_key" => "#{session_id}:cve-responder:20260903T200000Z" } } ]
      ))
      write_transcript(entries)
      url, requests, server, thread = start_listener

      run_hook(payload(agent_type: "cve-responder"), url: url)

      args = JSON.parse(requests.first[:body]).dig("params", "arguments")
      expect(args["run_key"]).to eq("#{session_id}:cve-responder:20260903T200000Z")
    ensure
      server&.close
      thread&.kill
    end

    it "reports failed when the run ended on an API error record" do
      entries = default_transcript
      entries << assistant(model: "claude-opus-5", id: "msg_err", output_tokens: 0, timestamp: "2026-09-03T20:00:50.000Z",
                           stop_reason: nil).merge("isApiErrorMessage" => true)
      write_transcript(entries)
      url, requests, server, thread = start_listener

      run_hook(payload(agent_type: "cve-responder"), url: url)

      expect(JSON.parse(requests.first[:body]).dig("params", "arguments", "outcome")).to eq("failed")
    ensure
      server&.close
      thread&.kill
    end

    it "never blocks: exits 0 with no call when the transcript is missing" do
      url, requests, server, thread = start_listener

      _out, _err, status = run_hook(payload(agent_type: "cve-responder"), url: url)

      expect(status.exitstatus).to eq(0)
      expect(requests).to be_empty
    ensure
      server&.close
      thread&.kill
    end
  end

  context "a subagent that is not a platform agent" do
    it "makes no call for a built-in or hand-authored subagent type" do
      write_skeleton("cve-responder")
      write_transcript(default_transcript)
      url, requests, server, thread = start_listener

      _out, _err, status = run_hook(payload(agent_type: "general-purpose"), url: url)

      expect(status.exitstatus).to eq(0)
      expect(requests).to be_empty
    ensure
      server&.close
      thread&.kill
    end

    it "makes no call for a same-named file that lacks the generated header (hand-authored)" do
      path = File.join(project_dir, ".claude", "agents", "powernode")
      FileUtils.mkdir_p(path)
      File.write(File.join(path, "cve-responder.md"), "---\nname: cve-responder\n---\nhand-written\n")
      write_transcript(default_transcript)
      url, requests, server, thread = start_listener

      run_hook(payload(agent_type: "cve-responder"), url: url)

      expect(requests).to be_empty
    ensure
      server&.close
      thread&.kill
    end
  end
end
