# frozen_string_literal: true

require "rails_helper"

# Deterministic preferred_provider resolution from operator text (dryrun §4 blocker).
#
# The account's configured providers are an authoritative, enumerable set, so a
# choice among them must never be free-generated by the LLM. Three live runs on
# ops-hub (2026-08-08/09) extracted three different WRONG values ('pro_cloud',
# 'pro_cloud', 'local_qemu') from objectives that named "the 'IPNode PVE'
# provider" explicitly. The worst case: 'local_qemu' IS configured, so F4's
# validation passed it, and the local-provider region scrub then destroyed the
# brief's correctly-captured regions ["dna","rna"] — one misextraction changed
# the target cloud AND silently dropped multi-region intent.
#
# Resolution layers under test:
#   1. TEXT EVIDENCE (authoritative): when the operator's utterance names exactly
#      one configured provider (by name, type, or id), that provider wins over
#      whatever the LLM extracted. Deterministic string matching — cannot
#      hallucinate.
#   2. CLOSED-SET PROMPT: when a catalog exists, the extraction prompt enumerates
#      the account's actual providers instead of a generic cloud vocabulary that
#      invited 'pro_cloud'/'aws' answers (and didn't even contain 'proxmox').
#   3. DATA-DRIVEN REGION SCRUB: the local-provider scrub consults configured
#      ProviderRegion.region_codes instead of unconditionally emptying regions,
#      and an UNCORROBORATED local pick that would destroy another provider's
#      configured regions is demoted to nil (composer asks) rather than
#      silently rerouting the plan.
RSpec.describe Ai::Provisioning::IntentCaptureService, "provider text evidence", type: :service do
  let(:account) { create(:account) }
  let(:user) { create(:user, account: account) }

  subject(:service) { described_class.new(account: account, user: user) }

  # The objective text used in the live runs — names the provider explicitly.
  let(:objective) do
    "Provision a 3-node stack across dna and rna using the 'IPNode PVE' provider"
  end

  def llm_brief(overrides = {})
    {
      "intent" => "provision a 3-node Powernode stack",
      "use_case" => "database",
      "scale" => { "initial" => 3, "target" => 3, "growth_profile" => "steady" },
      "regions" => %w[dna rna],
      "budget_cap_usd_monthly" => 5
    }.merge(overrides)
  end

  def capture(text:, llm: {})
    allow(service).to receive(:extract_brief_from_llm).and_return(llm_brief(llm))
    service.capture(natural_language: text)[:brief]
  end

  context "with a configured catalog (mirrors ops-hub)" do
    let!(:proxmox) do
      ::System::Provider.create!(account: account, name: "IPNode PVE", provider_type: "proxmox", enabled: true)
    end
    let!(:local) do
      ::System::Provider.create!(account: account, name: "local-qemu", provider_type: "local_qemu", enabled: true)
    end

    before do
      skip "system extension not loaded" unless defined?(::System::Provider)
      # The account factory bootstraps a "Pro Cloud" provider with
      # us-east-1/us-west-1 regions (M1 self-serve). Clear everything that
      # isn't the two providers above, or 'pro_cloud' extractions are
      # legitimately configured here and these examples stop testing anything.
      ::System::Provider.where(account_id: account.id).where.not(id: [proxmox.id, local.id]).destroy_all
      %w[dna rna].each do |code|
        ::System::ProviderRegion.create!(
          account: account, provider: proxmox, name: code, region_code: code, enabled: true
        )
      end
    end

    it "premise: catalog is exactly proxmox(dna,rna) + local_qemu(no regions)" do
      expect(::System::Provider.where(account_id: account.id, enabled: true).pluck(:provider_type))
        .to match_array(%w[proxmox local_qemu])
      expect(proxmox.provider_regions.pluck(:region_code)).to match_array(%w[dna rna])
      expect(local.provider_regions).to be_empty
    end

    describe "layer 1 — text evidence overrides the LLM" do
      it "corrects the observed misextraction: text names IPNode PVE, LLM said pro_cloud" do
        brief = capture(text: objective, llm: { "preferred_provider" => "pro_cloud" })
        expect(brief["preferred_provider"]).to eq("proxmox")
        expect(brief["regions"]).to match_array(%w[dna rna])
      end

      it "corrects the worst case: LLM hallucinated a DIFFERENT configured provider" do
        # 'local_qemu' is configured, so validation alone passes it and the
        # region scrub then destroys ["dna","rna"]. Text evidence must win.
        brief = capture(text: objective, llm: { "preferred_provider" => "local_qemu" })
        expect(brief["preferred_provider"]).to eq("proxmox")
        expect(brief["regions"]).to match_array(%w[dna rna])
      end

      it "fills preferred_provider from text when the LLM omitted it" do
        brief = capture(text: "deploy on proxmox please", llm: {})
        expect(brief["preferred_provider"]).to eq("proxmox")
      end

      it "matches the provider id in text" do
        brief = capture(text: "use provider #{proxmox.id} for this", llm: {})
        expect(brief["preferred_provider"]).to eq("proxmox")
      end

      it "matches name variants across hyphen/underscore/case differences" do
        brief = capture(text: "run it on Local QEMU", llm: {})
        expect(brief["preferred_provider"]).to eq("local_qemu")
      end

      it "does not override when the text names MORE THAN ONE configured provider" do
        # Negation ("not X") is beyond deterministic string matching, so a
        # multi-mention utterance yields no evidence and the LLM's constrained
        # pick stands. Regions kept empty here: an ambiguous pick carrying
        # ANOTHER provider's regions is the demotion case, covered below.
        brief = capture(
          text: "use local-qemu, not the IPNode PVE provider",
          llm: { "preferred_provider" => "local_qemu", "regions" => [] }
        )
        expect(brief["preferred_provider"]).to eq("local_qemu")
      end

      it "does not match a provider token embedded inside another word" do
        ::System::Provider.create!(account: account, name: "Amazon", provider_type: "aws", enabled: true)
        brief = capture(text: "fix the flaws in this stack", llm: {})
        expect(brief["preferred_provider"]).to be_nil
      end

      it "applies on the refine seam too (clarification answers name providers)" do
        allow(service).to receive(:extract_brief_from_llm).and_return({})
        brief = service.refine(brief: llm_brief, clarification: "Use the IPNode PVE provider")[:brief]
        expect(brief["preferred_provider"]).to eq("proxmox")
      end
    end

    describe "layer 3 — data-driven local-provider region scrub" do
      it "keeps regions the local provider actually has configured" do
        ::System::ProviderRegion.create!(
          account: account, provider: local, name: "workshop", region_code: "workshop", enabled: true
        )
        brief = capture(
          text: "run it on local-qemu in workshop",
          llm: { "preferred_provider" => "local_qemu", "regions" => %w[workshop us-east-1] }
        )
        expect(brief["preferred_provider"]).to eq("local_qemu")
        expect(brief["regions"]).to eq(%w[workshop])
      end

      it "still scrubs unconfigured cloud regions when the operator NAMED the local provider" do
        brief = capture(
          text: "run it on local-qemu",
          llm: { "preferred_provider" => "local_qemu", "regions" => %w[us-east-1] }
        )
        expect(brief["preferred_provider"]).to eq("local_qemu")
        expect(brief["regions"]).to eq([])
      end

      it "demotes an UNCORROBORATED local pick that would destroy another provider's regions" do
        # The exact silent-destruction case from the handoff: no provider named
        # in text, LLM hallucinates local_qemu, and ["dna","rna"] are the
        # proxmox provider's configured region_codes. Scrubbing here would
        # reroute the plan AND erase multi-region intent with no signal.
        expect(Rails.logger).to receive(:warn).with(/demot|uncorroborated/i).at_least(:once)
        allow(Rails.logger).to receive(:warn).and_call_original
        brief = capture(
          text: "Provision a 3-node stack across dna and rna",
          llm: { "preferred_provider" => "local_qemu" }
        )
        expect(brief["preferred_provider"]).to be_nil
        expect(brief["regions"]).to match_array(%w[dna rna])
      end

      it "scrubs as before when an uncorroborated local pick drops regions no provider has" do
        brief = capture(
          text: "spin up a stack",
          llm: { "preferred_provider" => "local_qemu", "regions" => %w[mars-1] }
        )
        expect(brief["preferred_provider"]).to eq("local_qemu")
        expect(brief["regions"]).to eq([])
      end
    end

    describe "layer 2 — closed-set prompt" do
      it "enumerates the account's configured providers instead of a generic vocabulary" do
        prompt = service.send(:build_brief_prompt, objective, {}, :capture)
        expect(prompt).to include("IPNode PVE")
        expect(prompt).to include("proxmox")
        expect(prompt).to include("local_qemu")
        expect(prompt).not_to match(/Hetzner|DigitalOcean|Vultr|Linode/)
      end

      it "instructs verbatim copy for unconfigured providers so the ask-path keeps the signal" do
        prompt = service.send(:build_brief_prompt, "deploy on AWS", {}, :capture)
        expect(prompt).to match(/verbatim/i)
      end
    end
  end

  context "core mode / empty catalog" do
    it "keeps the generic provider rule when no catalog is available" do
      allow(described_class).to receive(:provider_catalog_available?).and_return(false)
      prompt = service.send(:build_brief_prompt, "deploy on Hetzner", {}, :capture)
      expect(prompt).to include("preferred_provider")
      expect(prompt).to match(/Hetzner/i)
      expect(prompt).to include("lowercase")
    end

    it "keeps the unconditional region scrub for a local provider (no regions to consult)" do
      allow(described_class).to receive(:provider_catalog_available?).and_return(false)
      brief = capture(
        text: "spin up a stack",
        llm: { "preferred_provider" => "local_qemu", "regions" => %w[us-east-1] }
      )
      expect(brief["regions"]).to eq([])
    end
  end
end
