# frozen_string_literal: true

module Ai
  module ClaudeExport
    # Syncs platform Ai::Agent records to native Claude Code subagent skeletons
    # (<target_dir>/<slug>.md) so any Claude Code session can `Task(subagent_type:
    # "<slug>")` a platform-defined agent. The skeleton is a THIN MCP bootstrap —
    # it never duplicates the agent's system prompt or skill content. The
    # platform stays the single source of truth; the file just tells CC where to
    # fetch it (mcp__powernode__platform_get_agent / platform_get_skill_context)
    # at spawn time, so edits to the platform agent take effect on the NEXT spawn
    # with no regeneration needed.
    #
    # Agent scope resolution: GloballyScopable's `for_account` already unions
    # GLOBAL (account_id nil, platform-provided) agents with the given account's
    # own rows, so "active agents visible to the account" and "+ global agents"
    # collapse into ONE query — for_account(account_id).active. When an account
    # has overridden a global agent (same slug, its own row), both rows are
    # visible; `account_override_first` + a group-by-slug dedupe keeps only the
    # account's row for that slug, mirroring Ai::Agent.resolve_for /
    # AgentBackedService#resolve_service_agent (account override wins).
    #
    # Model tier: Ai::ModelTiers.classify(agent.resolved_model) maps to the CC
    # frontmatter `model:` value. frontier (Fable/Mythos) maps UNCONDITIONALLY to
    # "fable" — this does NOT consult Ai::FableRouting.enabled_for?/fable_model?
    # gating. That platform-side gate governs whether the PLATFORM may select
    # Fable for its own executions; it says nothing about Claude Code, which
    # carries its own separate Fable/Mythos entitlement from the CC subscription
    # tier. Do NOT "fix" this to check FableRouting — that would incorrectly
    # couple an unrelated platform kill-switch to the CC-side model picker.
    class AgentSkeletonSync
      GENERATED_HEADER = "<!-- generated by claude:sync_agents — do not edit; regenerate instead -->"

      TIER_TO_CC_MODEL = {
        light: "haiku",
        standard: "sonnet",
        reasoning: "opus",
        frontier: "fable"
      }.freeze

      Result = Struct.new(:written, :unchanged, :removed, :total, keyword_init: true)

      def initialize(account: nil, target_dir: nil)
        @account = account
        @target_dir = Pathname.new(target_dir.presence || default_target_dir)
      end

      # Writes/refreshes one skeleton per syncable agent, then removes stale
      # generated-header files for agents no longer syncable. Idempotent: a
      # file whose rendered content is unchanged is left untouched (mtime and
      # all) so re-running with no agent changes produces zero writes.
      def sync!
        FileUtils.mkdir_p(@target_dir)

        agents = syncable_agents
        skill_slugs = skill_slugs_by_agent(agents)
        written = []
        unchanged = []

        agents.each do |agent|
          key = sync_key(agent)
          path = @target_dir.join("#{key}.md")
          content = render(agent, skill_slugs[agent.id] || [])

          if File.exist?(path) && File.read(path) == content
            unchanged << key
          else
            File.write(path, content)
            written << key
          end
        end

        removed = cleanup_stale(agents.map { |agent| sync_key(agent) })

        Result.new(written: written, unchanged: unchanged, removed: removed, total: agents.size)
      end

      private

      def default_target_dir
        Rails.root.join("..", ".claude", "agents", "powernode")
      end

      def syncable_agents
        scope = ::Ai::Agent.for_account(@account&.id).active.account_override_first
        scope.group_by { |agent| sync_key(agent) }
             .transform_values(&:first)
             .values
             .sort_by { |agent| sync_key(agent) }
      end

      # One query for the whole syncable set (never N+1): #skill_slugs on
      # Ai::Agent is a per-record pluck, so calling it inside the #sync! loop
      # would issue one query per agent. Batching the same join/filter here
      # (mirrors Ai::Agent#skill_slugs) keeps it to a single round trip.
      def skill_slugs_by_agent(agents)
        return {} if agents.empty?

        ::Ai::AgentSkill.where(ai_agent_id: agents.map(&:id), is_active: true)
                        .joins(:skill)
                        .where(ai_skills: { status: "active" })
                        .pluck(:ai_agent_id, Arel.sql("ai_skills.slug"))
                        .each_with_object(Hash.new { |h, k| h[k] = [] }) { |(agent_id, slug), h| h[agent_id] << slug }
      end

      # Filesystem-safe, unique-across-the-output-set identifier. The agent
      # slug is presence/format-validated at the model level, so the fallback
      # only guards a defensive edge case (e.g. a legacy blank slug).
      def sync_key(agent)
        agent.slug.presence || agent.name.to_s.parameterize.presence || "agent-#{agent.id}"
      end

      def render(agent, skills)
        agent.using_account(@account)
        tier = ::Ai::ModelTiers.classify(agent.resolved_model)
        cc_model = TIER_TO_CC_MODEL.fetch(tier, TIER_TO_CC_MODEL[::Ai::ModelTiers::DEFAULT_TIER])

        frontmatter = {
          "name" => sync_key(agent),
          "description" => frontmatter_description(agent, tier),
          "model" => cc_model
        }

        "#{YAML.dump(frontmatter)}---\n\n#{body(agent, tier, skills)}\n"
      end

      # Reasoning/frontier tiers MUST articulate when spawning is warranted vs
      # a cheaper agent — this is the CC delegation surface a caller reads
      # before deciding to Task() this agent, so the guidance lives in
      # `description`, not just the body.
      def frontmatter_description(agent, tier)
        base = agent.description.presence || "Powernode platform agent \"#{agent.name}\" (#{agent.agent_type})."

        case tier
        when :frontier
          "#{base} FRONTIER-tier (Fable) delegation surface: spawn ONLY when the task genuinely needs " \
            "frontier-class reasoning, novel synthesis, or high-stakes judgment that a reasoning-tier (Opus) " \
            "agent would likely fall short on. For routine, mechanical, or well-scoped work, prefer a cheaper " \
            "agent (reasoning/standard/light-tier) instead — frontier is the most expensive option and should " \
            "be the exception, not the default."
        when :reasoning
          "#{base} REASONING-tier (Opus) delegation surface: spawn when the task needs multi-step reasoning, " \
            "architectural or design judgment, or cross-file analysis that a standard-tier agent is likely to " \
            "get wrong. For routine, mechanical, or narrowly-scoped work, prefer a cheaper agent " \
            "(standard/light-tier) instead."
        else
          base
        end
      end

      def body(agent, tier, skills)
        lines = [
          "This is the Claude Code counterpart of the Powernode platform agent \"#{agent.name}\" (id `#{agent.id}`).",
          "",
          GENERATED_HEADER,
          "",
          "On start, in order:",
          "1. Fetch your operating instructions via `mcp__powernode__platform_get_agent` with " \
            "`agent_id: \"#{agent.id}\"` and adopt the returned `system_prompt` as your instructions for this task."
        ]

        step = 2
        if skills.any?
          lines << "#{step}. Fetch skill context via `mcp__powernode__platform_get_skill_context` with " \
            "`agent_id: \"#{agent.id}\"` (mode: \"manifest\") for the attached skill(s): #{skills.sort.join(', ')}."
          step += 1
        end

        lines << "#{step}. Operate strictly under the fetched system prompt and skill context for the remainder " \
          "of this task — this file intentionally carries NO duplicated prompt content; the platform agent " \
          "record is the source of truth."

        if tier == :frontier
          lines << ""
          lines << "Before starting, state in one sentence why frontier capability is required for this " \
            "delegated task. If it is not genuinely required, complete the task anyway — gracefully, do not " \
            "refuse — and note in your final response that a lower tier would likely have sufficed."
        end

        lines.join("\n")
      end

      # Removes .md files in target_dir that carry our generated header but are
      # no longer in the current syncable set. Never touches a file without the
      # header — hand-authored agents elsewhere are untouched by construction
      # (different directory), but this guard also protects a hand-authored file
      # that happens to share this directory.
      def cleanup_stale(keep_keys)
        removed = []
        return removed unless @target_dir.exist?

        keep = keep_keys.to_set
        Dir.glob(@target_dir.join("*.md")).each do |path|
          key = File.basename(path, ".md")
          next if keep.include?(key)
          next unless File.read(path).include?(GENERATED_HEADER)

          File.delete(path)
          removed << key
        end
        removed
      end
    end
  end
end
