# frozen_string_literal: true

module Ai
  module ClaudeExport
    # NOT the platform-agent seed: this EXPORTS platform Ai::Agent records OUT as Claude Code
    # skeletons; server/db/seeds/claude_agents_seed.rb is the inverse — it seeds PLATFORM agents INTO the DB.
    #
    # Syncs platform Ai::Agent records to native Claude Code subagent skeletons
    # (<target_dir>/<slug>.md) so any Claude Code session can `Agent(subagent_type:
    # "<slug>")` a platform-defined agent. The skeleton is a THIN MCP bootstrap —
    # it never duplicates the agent's system prompt or skill content. The
    # platform stays the single source of truth; the file just tells CC where to
    # fetch it (mcp__powernode__platform_get_agent / platform_get_skill_context)
    # at spawn time, so edits to the platform agent take effect on the NEXT spawn
    # with no regeneration needed.
    #
    # ENVIRONMENT-INDEPENDENT (HIER-P1B item 1): the body fetches by SLUG, never
    # by the per-install agent UUID (ops-hub ids != dev ids, so a committed file
    # carrying an id would be wrong somewhere). get_agent resolves the slug
    # override-aware (Ai::Agent.resolve_for), so an account's clone of a
    # canonical wins on that install, and the returned `id` is what the skill
    # step feeds to get_skill_context.
    #
    # TWO SCOPES, TWO DIRECTORIES (canonical rule: official agents are GLOBAL
    # seeded canonicals and the platform is the source of truth):
    #   * no account  -> Ai::Routing::RoutableAgents.canonical, written to
    #                    .claude/agents/powernode/ and COMMITTED (freshness-gated
    #                    by scripts/check-claude-agents-fresh.sh);
    #   * account:    -> RoutableAgents.owned_by(account) — the account's own
    #                    rows (clones + own agents) ONLY, written to the
    #                    gitignored .claude/agents/powernode-local/.
    # A committed canonical file is therefore never wrong on another install,
    # and a local clone never leaks into the public tree.
    #
    # What each skeleton carries (items 3/4/9): a ROUTING description
    # (RoutingDescription — trigger + exclusion, what the CC Agent tool routes
    # on) plus the tier guidance below; a `tools:` allowlist (ToolAllowlist —
    # derived from the agent's tool access the way AgentToolBridgeService scopes
    # it); a Delegation section from the agent's Ai::DelegationPolicy and
    # lineage parent; and Ai::Agent::BASE_GUARDRAILS verbatim as the always-on
    # floor (the fetched prompt already prepends them natively — the body says so).
    #
    # CANONICAL SCOPE READS ONLY GLOBALLY-SCOPED ROWS (see #canonical_only?):
    # delegation policies, intervention policies and lineage edges all carry a
    # NOT NULL account_id, so they are account data and never reach a COMMITTED
    # file — the canonical render would otherwise differ per install (and per
    # account) and publish one tenant's governance configuration. In the
    # canonical files "Reports to" comes from the agent's own parent_agent_id
    # column and the routing triggers from the agent's row plus its GLOBAL bound
    # skills — including the policy DOMAINS those skills' action categories map
    # to (HIER-P2G, see #domains_by_agent); the gitignored powernode-local/
    # export reads all four, scoped to the account it was run for.
    #
    # Model tier: Ai::ModelTiers.classify(agent.resolved_model) maps to the CC
    # frontmatter `model:` value. frontier (Fable/Mythos) maps UNCONDITIONALLY to
    # "fable" — this does NOT consult Ai::FableRouting.enabled_for?/fable_model?
    # gating. That platform-side gate governs whether the PLATFORM may select
    # Fable for its own executions; it says nothing about Claude Code, which
    # carries its own separate Fable/Mythos entitlement from the CC subscription
    # tier. Do NOT "fix" this to check FableRouting — that would incorrectly
    # couple an unrelated platform kill-switch to the CC-side model picker.
    class AgentSkeletonSync
      GENERATED_HEADER = "<!-- generated by claude:sync_agents — do not edit; regenerate instead -->"
      CANONICAL_DIR = "powernode"
      LOCAL_DIR = "powernode-local"

      TIER_TO_CC_MODEL = {
        light: "haiku",
        standard: "sonnet",
        reasoning: "opus",
        frontier: "fable"
      }.freeze

      Result = Struct.new(:written, :unchanged, :removed, :total, keyword_init: true)

      # @param account [Account, nil] nil exports the canonical set; an account
      #   exports that account's own rows only (see class comment)
      def initialize(account: nil, target_dir: nil)
        @account = account
        @target_dir = Pathname.new(target_dir.presence || default_target_dir)
      end

      def canonical_scope?
        @account.nil?
      end

      # Writes/refreshes one skeleton per syncable agent, then removes stale
      # generated-header files for agents no longer syncable. Idempotent: a
      # file whose rendered content is unchanged is left untouched (mtime and
      # all) so re-running with no agent changes produces zero writes.
      def sync!
        FileUtils.mkdir_p(@target_dir)

        agents = syncable_agents
        context = build_context(agents)
        written = []
        unchanged = []

        agents.each do |agent|
          key = sync_key(agent)
          path = @target_dir.join("#{key}.md")
          content = render(agent, context)

          if File.exist?(path) && File.read(path) == content
            unchanged << key
          else
            File.write(path, content)
            written << key
          end
        end

        # An EMPTY canonical set is a database that never ran the agent seeds
        # (a fresh dev cell), not a platform with no agents: cleaning up
        # against it would delete every committed skeleton, and the Stop hook
        # runs this after any seed edit. Refuse the cleanup, keep the files.
        removed = if agents.empty? && canonical_scope?
          Rails.logger.warn("[claude:sync_agents] canonical scope resolved 0 agents — " \
                            "leaving #{@target_dir} untouched (unseeded database?)")
          []
        else
          cleanup_stale(agents.map { |agent| sync_key(agent) })
        end

        Result.new(written: written, unchanged: unchanged, removed: removed, total: agents.size)
      end

      private

      def default_target_dir
        Rails.root.join("..", ".claude", "agents", canonical_scope? ? CANONICAL_DIR : LOCAL_DIR)
      end

      # ONE definition of the exportable set, shared with the router
      # (Ai::Routing::RoutableAgents) so `platform.route_task` names exactly the
      # subagent_types this file set carries.
      def syncable_agents
        canonical_scope? ? ::Ai::Routing::RoutableAgents.canonical : ::Ai::Routing::RoutableAgents.owned_by(@account.id)
      end

      def sync_key(agent)
        ::Ai::Routing::RoutableAgents.key(agent)
      end

      # Everything the renderer needs, fetched in ONE query per relation for the
      # whole set (never N+1 inside the #sync! loop): skills, policy domains,
      # delegation policies, lineage parents, the registry snapshot for the tool
      # allowlist, and the routing descriptions (which need every sibling).
      def build_context(agents)
        ids = agents.map(&:id)
        skills = skills_by_agent(ids)
        domains = domains_by_agent(ids, skills)
        {
          skills: skills,
          domains: domains,
          delegation: delegation_by_agent(ids),
          parents: parents_by_agent(agents),
          registry: ToolAllowlist::Registry.snapshot,
          descriptions: RoutingDescription.build_all(agents, skills_by_agent: skills, domains_by_agent: domains)
        }
      end

      # CANONICAL SCOPE READS ONLY GLOBALLY-SCOPED ROWS.
      #
      # A canonical skeleton is COMMITTED and freshness-gated by diff, so it
      # must render byte-identically on every install (item 1). Any relation
      # whose rows are account-scoped therefore cannot contribute to it: two
      # installs — or one install with two accounts — would render different
      # files and the gate would fail for a reason nobody can fix. The schema
      # settles which relations those are:
      #
      #   ai_agent_skills          NO account_id  -> usable, joined to GLOBAL skills
      #   ai_agents.parent_agent_id a column on the (global) agent -> usable
      #   ai_intervention_policies account_id NOT NULL -> account data, EXCLUDED
      #   ai_delegation_policies   account_id NOT NULL -> account data, EXCLUDED
      #   ai_agent_lineages        account_id NOT NULL -> account data, EXCLUDED
      #
      # There is no such thing as a canonical intervention/delegation/lineage
      # row (the columns are NOT NULL), and the seeds key them on the platform
      # admin account (db/seeds/ai_agent_hierarchy_seed.rb: "The delegation rows
      # are keyed on that SAME account rather than as canonical account_id-NULL
      # rows"), so an earlier "prefer the global row, else rows.first" fallback
      # committed one tenant's governance configuration to a public repo. In
      # ACCOUNT scope (.claude/agents/powernode-local/, gitignored) all four are
      # read, scoped to that account — that export is per-install by design.
      def canonical_only?
        canonical_scope?
      end

      # Active bindings to active skills, one query (mirrors Ai::Agent#skill_slugs,
      # which is a per-record pluck). Whole skill rows: the routing description
      # reads name/tags, the body lists slugs. Sorted by slug: the rendered
      # output must be DETERMINISTIC (the freshness gate diffs it byte for byte),
      # and row order out of an unordered query is not.
      #
      # The join table carries no account, so canonical scope restricts to
      # GLOBAL skills (the seeds create every platform skill global —
      # db/seeds/ai_skills_seed.rb: "Ai::Skill rows are seeded global"); an
      # account binding its own skill to a canonical agent must not change the
      # committed file.
      def skills_by_agent(ids)
        return {} if ids.empty?

        scope = ::Ai::AgentSkill.where(ai_agent_id: ids, is_active: true)
                                .joins(:skill).where(ai_skills: { status: "active" })
        scope = scope.where(ai_skills: { account_id: nil }) if canonical_only?
        scope.includes(:skill)
             .each_with_object(Hash.new { |h, k| h[k] = [] }) { |binding, h| h[binding.ai_agent_id] << binding.skill }
             .transform_values { |skills| skills.sort_by(&:slug) }
      end

      # Policy domains (PolicyDomains — the owning extension registers its
      # category → domain table at boot).
      #
      # ACCOUNT scope: the agent's active intervention-policy categories for
      # that account. The rows are account data (account_id NOT NULL, see
      # canonical_only?), so they never reach a canonical file.
      #
      # CANONICAL scope (HIER-P2G): the action categories the agent's GLOBAL
      # bound skills carry in `metadata.action_category` — the seeds stamp each
      # executor-backed skill with its executor's gate category — mapped
      # through the REGISTERED domain table only. Global rows, deterministic on
      # every install, and the domain names are what the extension registered,
      # so the routing description and the sibling ranking see the extension's
      # own vocabulary ("storage", "disk image", "topology") rather than a
      # leading-token guess: the heuristic fallback would turn every unmapped
      # category into a spurious trigger ("attribute", "fulfill"), so it is
      # not consulted here.
      def domains_by_agent(ids, skills_by_agent)
        return {} if ids.empty?
        return domains_from_skills(skills_by_agent) if canonical_only?

        ::Ai::InterventionPolicy.where(ai_agent_id: ids, is_active: true, account_id: @account.id)
                                .distinct.pluck(:ai_agent_id, :action_category)
                                .group_by(&:first)
                                .transform_values { |rows| PolicyDomains.for_categories(rows.map(&:last).sort) }
      end

      def domains_from_skills(skills_by_agent)
        registered = PolicyDomains.registered.map(&:first).to_set
        skills_by_agent.each_with_object({}) do |(agent_id, skills), out|
          categories = skills.filter_map do |skill|
            skill.metadata.is_a?(Hash) ? skill.metadata["action_category"].to_s.strip.presence : nil
          end.uniq.sort
          domains = PolicyDomains.for_categories(categories).select { |domain| registered.include?(domain) }
          out[agent_id] = domains if domains.any?
        end
      end

      # One policy per agent, the account's own row. ACCOUNT SCOPE ONLY — see
      # canonical_only?: ai_delegation_policies.account_id is NOT NULL, so no
      # delegation policy is ever canonical and none may be committed.
      def delegation_by_agent(ids)
        return {} if ids.empty? || canonical_only?

        ::Ai::DelegationPolicy.where(agent_id: ids, account_id: @account.id)
                              .order(:created_at, :id).group_by(&:agent_id)
                              .transform_values(&:first)
      end

      # Lineage parent: the agent's own parent_agent_id column (a property of
      # the global row, so canonical-safe) and — in ACCOUNT scope only — the
      # account's active Ai::AgentLineage edge as a fallback. Resolved to the
      # parent's slug for "Reports to".
      def parents_by_agent(agents)
        return {} if agents.empty?

        parent_ids = agents.to_h { |agent| [ agent.id, agent.parent_agent_id ] }
        unless canonical_only?
          ::Ai::AgentLineage.active.where(child_agent_id: agents.map(&:id), account_id: @account.id)
                            .order(:spawned_at, :id).pluck(:child_agent_id, :parent_agent_id)
                            .each { |child_id, parent_id| parent_ids[child_id] ||= parent_id }
        end
        parents = ::Ai::Agent.where(id: parent_ids.values.compact.uniq).index_by(&:id)
        parent_ids.transform_values { |parent_id| parent_id && parents[parent_id] }.compact
      end

      def render(agent, context)
        tier = tier_for(agent)
        cc_model = TIER_TO_CC_MODEL.fetch(tier, TIER_TO_CC_MODEL[::Ai::ModelTiers::DEFAULT_TIER])
        skills = context[:skills][agent.id] || []

        frontmatter = {
          "name" => sync_key(agent),
          "description" => frontmatter_description(context[:descriptions][sync_key(agent)], tier),
          "model" => cc_model
        }
        tools = ToolAllowlist.for(agent, registry: context[:registry])
        frontmatter["tools"] = tools.join(", ") if tools

        # line_width: -1 keeps every scalar on ONE physical line — Psych's default
        # folding of long plain scalars is valid YAML but not every frontmatter
        # reader unfolds it, and `tools:` is parsed as a comma-separated string.
        "#{YAML.dump(frontmatter, line_width: -1)}---\n\n#{body(agent, tier, skills, context)}\n"
      end

      # Model tier. The agent's DECLARED requirement first
      # (mcp_metadata.model_config.model_requirements.tier — what the seeds
      # state), then a pinned model's family (model_config.model). Only in
      # ACCOUNT scope does the install's runtime resolution (resolved_model —
      # Ai::AgentModelSelector over THIS account's credentialed providers) act
      # as the fallback: a canonical file is committed and must render the same
      # on every install, so it never consults provider state (item 1).
      def tier_for(agent)
        config = agent.mcp_metadata.is_a?(Hash) ? agent.mcp_metadata["model_config"] : nil
        config = {} unless config.is_a?(Hash)

        declared = config.dig("model_requirements", "tier").to_s.presence
        return declared.to_sym if declared && TIER_TO_CC_MODEL.key?(declared.to_sym)

        pinned = config["model"].to_s.presence
        return ::Ai::ModelTiers.classify(pinned) if pinned
        return ::Ai::ModelTiers::DEFAULT_TIER if canonical_scope?

        agent.using_account(@account)
        ::Ai::ModelTiers.classify(agent.resolved_model)
      end

      # The routing description (trigger + exclusion) comes first — it is what
      # the CC Agent tool routes on. Reasoning/frontier tiers then MUST
      # articulate when spawning is warranted vs a cheaper agent — the CC
      # delegation surface a caller reads before deciding to Agent() this agent.
      def frontmatter_description(routing, tier)
        case tier
        when :frontier
          "#{routing} FRONTIER-tier (Fable) delegation surface: spawn ONLY when the task genuinely needs " \
            "frontier-class reasoning, novel synthesis, or high-stakes judgment that a reasoning-tier (Opus) " \
            "agent would likely fall short on. For routine, mechanical, or well-scoped work, prefer a cheaper " \
            "agent (reasoning/standard/light-tier) instead — frontier is the most expensive option and should " \
            "be the exception, not the default."
        when :reasoning
          "#{routing} REASONING-tier (Opus) delegation surface: spawn when the task needs multi-step reasoning, " \
            "architectural or design judgment, or cross-file analysis that a standard-tier agent is likely to " \
            "get wrong. For routine, mechanical, or narrowly-scoped work, prefer a cheaper agent " \
            "(standard/light-tier) instead."
        else
          routing
        end
      end

      def body(agent, tier, skills, context)
        slug = sync_key(agent)
        lines = [
          "This is the Claude Code counterpart of the Powernode platform agent \"#{agent.name}\" (slug `#{slug}`).",
          "",
          GENERATED_HEADER,
          "",
          "On start, in order:",
          "1. Fetch your operating instructions via `mcp__powernode__platform_get_agent` with " \
            "`slug: \"#{slug}\"` and adopt the returned `system_prompt` as your instructions for this task. " \
            "The slug is stable across installs; the platform resolves it override-aware (an account's clone " \
            "wins over the canonical), and the returned `id` is this install's agent id."
        ]

        step = 2
        if skills.any?
          lines << "#{step}. Fetch skill context via `mcp__powernode__platform_get_skill_context` with " \
            "`agent_id: <the id returned in step 1>` (mode: \"manifest\", input_text: your task) for the " \
            "attached skill(s): #{skills.map(&:slug).sort.join(', ')}."
          step += 1
        end

        lines << "#{step}. Operate strictly under the fetched system prompt and skill context for the remainder " \
          "of this task — this file intentionally carries NO duplicated prompt content; the platform agent " \
          "record is the source of truth."
        step += 1

        lines << "#{step}. #{self_report_instruction(slug)}"

        if tier == :frontier
          lines << ""
          lines << "Before starting, state in one sentence why frontier capability is required for this " \
            "delegated task. If it is not genuinely required, complete the task anyway — gracefully, do not " \
            "refuse — and note in your final response that a lower tier would likely have sufficed."
        end

        delegation = delegation_section(context[:delegation][agent.id], context[:parents][agent.id])
        lines.concat([ "" ] + delegation) if delegation.any?

        lines.concat([
          "",
          "## Baseline guardrails (always-on)",
          "",
          "The platform prepends these to every agent's system prompt natively (`Ai::Agent::BASE_GUARDRAILS`), " \
            "so the prompt fetched in step 1 already carries them; they are repeated here verbatim as the " \
            "always-on floor for this subagent, not as a second instruction set.",
          "",
          ::Ai::Agent::BASE_GUARDRAILS
        ])

        lines.join("\n")
      end

      # HIER-P1C item 4(b): the run reports itself back so the platform's
      # execution, trust and model statistics see it. This is the FALLBACK for
      # a checkout with the SubagentStop hook (.claude/hooks/subagent-report.sh)
      # disabled; when the hook runs too, it copies this self-report's run_key
      # out of the transcript, so the platform sees ONE row (idempotent on
      # run_key). The run_key shape is the contract the hook parses — keep the
      # two in step.
      def self_report_instruction(slug)
        "Before returning, report this run so the platform's statistics see it: call " \
          "`mcp__powernode__platform_record_agent_execution` with `agent_slug: \"#{slug}\"`, `model` (the model id " \
          "you are running as), `outcome` (completed | failed | cancelled), `duration_ms`, `tokens` " \
          "({ input, output }), a `task_digest` of at most 500 characters with no secrets, and " \
          "`run_key: \"<$CLAUDE_CODE_SESSION_ID>:#{slug}:<UTC start time as YYYYMMDDTHHMMSSZ>\"` " \
          "(read CLAUDE_CODE_SESSION_ID from your environment; note the start time when you begin). " \
          "The verb records history only — it is idempotent on run_key and never acts on the platform."
      end

      # Rendered only when something exists: the lineage parent (whom this agent
      # reports to) and/or the delegation policy (whom it may delegate to).
      def delegation_section(policy, parent)
        return [] if policy.nil? && parent.nil?

        lines = [ "## Delegation", "" ]
        lines << "- Reports to: `#{sync_key(parent)}` (#{parent.name})" if parent
        if policy
          types = Array(policy.allowed_delegate_types).map(&:to_s).reject(&:blank?)
          lines << "- May delegate to: #{types.any? ? "#{types.join(', ')}#{delegate_type_warning(types)}" : 'any agent type'}"
          lines << "- Max delegation depth: #{policy.max_depth}"
          lines << "- Inheritance: #{policy.inheritance_policy}"
          actions = Array(policy.delegatable_actions).map(&:to_s).reject(&:blank?)
          lines << "- Delegatable actions: #{actions.join(', ')}" if actions.any?
        end
        lines
      end

      # `allowed_delegate_types` is compared against Ai::Agent#agent_type by
      # every reader (Ai::DelegationPolicy#allows_delegate_type?, from
      # Ai::Autonomy::DelegationAuthorityService and Ai::Routing::AgentRouterService,
      # which filters its candidate pool with it). A row naming SKILL SLUGS or
      # policy categories instead does not narrow delegation — it refuses ALL of
      # it and empties the router pool. Rendering the list silently would hand a
      # subagent a delegation surface that cannot fire, so the entries that are
      # not agent types are named as such in the file.
      #
      # The vocabulary is read from the model's own inclusion validator (the
      # declaration site), never a copy of the literal that could drift.
      def agent_type_vocabulary
        # `options[:in]` is the literal the validation declares; #delimiter is
        # private in this Rails version, and a respond_to? guard would report
        # false for it and silently yield an EMPTY vocabulary — which would mark
        # every delegate type unknown.
        @agent_type_vocabulary ||= ::Ai::Agent.validators_on(:agent_type)
                                              .grep(ActiveModel::Validations::InclusionValidator)
                                              .flat_map { |validator| Array(validator.options[:in] || validator.options[:within]) }
                                              .map(&:to_s).to_set
      end

      def delegate_type_warning(types)
        unknown = types.reject { |type| agent_type_vocabulary.include?(type) }
        return "" if unknown.none?

        known = types - unknown
        effect = known.any? ? "only #{known.join(', ')}" : "NO agent type at all"
        " — NOTE: #{unknown.join(', ')} #{unknown.one? ? 'is not an' : 'are not'} agent type#{'s' unless unknown.one?} " \
          "(delegation is matched on Ai::Agent#agent_type), so this policy in fact allows #{effect}"
      end

      # Removes .md files in target_dir that carry our generated header but are
      # no longer in the current syncable set. Never touches a file without the
      # header — hand-authored agents elsewhere are untouched by construction
      # (different directory), but this guard also protects a hand-authored file
      # that happens to share this directory.
      def cleanup_stale(keep_keys)
        removed = []
        return removed unless @target_dir.exist?

        keep = keep_keys.to_set
        Dir.glob(@target_dir.join("*.md")).each do |path|
          key = File.basename(path, ".md")
          next if keep.include?(key)
          next unless File.read(path).include?(GENERATED_HEADER)

          File.delete(path)
          removed << key
        end
        removed
      end
    end
  end
end
