# frozen_string_literal: true

# IMP-99e8e4701150 — every existing `users.backup_codes` row holds an array of
# PLAINTEXT codes (encrypted at rest via `encrypts`, but recoverable by
# anything that can decrypt the column — the same class of risk `encrypts`
# alone accepts for `password_digest`, which is why passwords are never just
# `encrypts`, they're bcrypt-digested first). From here on the column holds
# one-way bcrypt digests instead, exactly like `password_digest` and
# `reset_token_digest` — verified by comparison, never decrypted back to the
# original code.
#
# Pre-production, no legacy dual-read: this migration hashes every existing
# row IN PLACE. A user with backup codes generated before this deploy keeps
# the same codes; the model's own #verify_backup_code (BCrypt::Password
# comparison) can validate them exactly as it validates a digest generated by
# #confirm_two_factor_setup! / #regenerate_backup_codes! afterward — from the
# model's perspective there is no distinction between a hashed-in-place code
# and one hashed at generation time.
#
# A LOCAL migration-scoped class, not the app's User model: this needs the
# exact same `encrypts`/`serialize` shape User declares for `backup_codes` to
# read/write the column correctly, without coupling a historical data
# migration to wherever the live model's column list drifts to next.
class HashExistingTwoFactorBackupCodes < ActiveRecord::Migration[8.1]
  class MigrationUser < ActiveRecord::Base
    self.table_name = "users"
    encrypts :backup_codes
    serialize :backup_codes, coder: JSON
  end

  # Matches a bcrypt digest's own format (`$2a$`/`$2b$`/`$2y$`, cost, salt+hash)
  # — NOT a claim about origin. Idempotency check, so re-running this
  # migration (or running it against a row some other write already hashed)
  # never double-hashes a digest into an unverifiable value.
  ALREADY_HASHED = /\A\$2[aby]\$\d{2}\$/

  def up
    MigrationUser.where.not(backup_codes: nil).find_each do |user|
      codes = Array(user.backup_codes)
      next if codes.empty?

      # A boolean flag, NOT `digests != codes`: BCrypt::Password overrides
      # `==` to mean "is this the plaintext this hash verifies against" —
      # `BCrypt::Password.create("AAAAAAAA") == "AAAAAAAA"` is TRUE. An
      # array-equality comparison between the freshly-hashed digests and the
      # original plaintext codes would therefore read as "unchanged" and
      # skip the write on every row that most needs it. `.to_s` on the
      # created digest also matters here, independent of that gotcha: it
      # stores a plain String (what the column always held before and what
      # #verify_backup_code always reads back), not a BCrypt::Password
      # instance carrying that same surprising `==`.
      changed = false
      digests = codes.map do |code|
        code = code.to_s
        next code if ALREADY_HASHED.match?(code)

        changed = true
        # Cost 10, matching User::BACKUP_CODE_BCRYPT_COST (IMP-99e8e4701150
        # review M1) — kept as a literal here rather than referencing the
        # model constant, per this file's own stated reason for a
        # migration-local class: never couple a historical migration to
        # wherever the live model drifts to next.
        BCrypt::Password.create(code, cost: 10).to_s
      end

      user.update_column(:backup_codes, digests) if changed
    end
  end

  # The plaintext codes are gone the moment they're hashed — there is nothing
  # to reverse this migration back to.
  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
