# frozen_string_literal: true

module Ai
  # Shared plumbing for the media generation services (audio / image / video):
  # per-account provider + credential resolution, default-model pick from the
  # provider record, API error-body parsing, and FileStorage persistence of the
  # generated bytes.
  #
  # Including services must define:
  #   PROVIDER_TYPE   — the Ai::Provider#provider_type to resolve ("elevenlabs", "openai", "runway")
  #   GenerationError — the service's error class (raised by all shared helpers)
  # and expose `account` and `user` readers.
  module MediaGenerationCommon
    private

    def resolve_provider_and_credential
      provider = Ai::Provider.where(account: account, provider_type: self.class::PROVIDER_TYPE, is_active: true).first
      generation_error!("No active #{self.class::PROVIDER_TYPE} provider found for account #{account.id}") unless provider

      credential = provider.provider_credentials.active.where(account_id: account.id).first
      generation_error!("No active credential found for #{self.class::PROVIDER_TYPE} provider #{provider.id}") unless credential

      [provider, credential]
    end

    def default_model(provider)
      first = provider.supported_models&.first
      model = first.is_a?(Hash) ? (first["id"] || first["name"]) : first
      model || provider.metadata&.dig("default_model") ||
        generation_error!("No model configured for #{self.class::PROVIDER_TYPE} provider")
    end

    # Best-effort human-readable error from a provider API response body.
    # Tries the error-detail shapes used by the supported providers in order:
    # ElevenLabs (detail.message / detail), OpenAI + Runway (error.message /
    # error / message), falling back to the HTTP status.
    def api_error(resp)
      body = begin
        JSON.parse(resp.body.to_s)
      rescue JSON::ParserError
        { "error" => resp.body.to_s }
      end
      body.dig("detail", "message") || body["detail"] ||
        body.dig("error", "message") || body["error"] || body["message"] ||
        "HTTP #{resp.status}"
    end

    # Store generated bytes as an ai_generated FileManagement::Object.
    # Returns nil (skipping storage) when no file storage is configured.
    def store_generated_file(bytes, filename:, content_type:, metadata:)
      io = StringIO.new(bytes)
      FileStorageService.new(account).upload_file(
        io,
        filename: filename,
        content_type: content_type,
        category: "ai_generated",
        uploaded_by_id: user&.id,
        metadata: metadata.merge(generated_at: Time.current.iso8601)
      )
    rescue FileStorageService::StorageNotFoundError => e
      Rails.logger.warn "[#{self.class.name.demodulize}] No file storage configured, skipping upload: #{e.message}"
      nil
    end

    def media_filename(text, prefix:, ext:)
      slug = text.parameterize[0..40]
      "#{prefix}_#{slug}_#{SecureRandom.hex(4)}.#{ext}"
    end

    def generation_error!(message)
      raise self.class::GenerationError, message
    end
  end
end
