// Findings reporter for the AI smoke harness.
//
// Classifies each non-ok result into a severity bucket and writes both a
// human-readable markdown report (docs/operations/) and a machine-readable JSON
// artifact. Severity heuristics:
//   critical    5xx server errors, network failures/timeouts (status 0)
//   high        422/400/409 on a controlled-valid request (real contract bug)
//   investigate 404 (could be a missing fixture OR a stale manifest path)
//   auth        401/403 (token scope / permission — usually env, not a bug)
//   medium      any other non-2xx

import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '../..');

function classify(rec) {
  const s = rec.status;
  if (s === 0 || s >= 500) return 'critical';
  if (s === 422 || s === 400 || s === 409) return 'high';
  if (s === 404) return 'investigate';
  if (s === 401 || s === 403) return 'auth';
  return 'medium';
}

const SEV_ORDER = ['critical', 'high', 'investigate', 'medium', 'auth'];

function isoNow() {
  // Date is allowed in standalone node scripts (unlike workflow scripts).
  return new Date().toISOString();
}

export function writeReport(results, meta) {
  const findings = results.filter((r) => !r.ok && !r.skipped).map((r) => ({ ...r, severity: classify(r) }));
  const skipped = results.filter((r) => r.skipped);
  const passed = results.filter((r) => r.ok && !r.skipped);

  const bySeverity = {};
  for (const f of findings) bySeverity[f.severity] = (bySeverity[f.severity] || 0) + 1;

  const byDomain = {};
  for (const r of results) {
    const d = (byDomain[r.domain] ||= { total: 0, ok: 0, findings: 0, skipped: 0 });
    d.total++;
    if (r.skipped) d.skipped++;
    else if (r.ok) d.ok++;
    else d.findings++;
  }

  const mdPath = meta.mdPath || path.join(REPO, 'docs/operations/ai-smoke-findings.md');
  const jsonPath = meta.jsonPath || path.join(REPO, 'docs/operations/ai-smoke-findings.json');
  fs.mkdirSync(path.dirname(mdPath), { recursive: true });
  fs.mkdirSync(path.dirname(jsonPath), { recursive: true });

  // ----- markdown -----
  const lines = [];
  lines.push('# AI Frontend-Actions Smoke — Findings');
  lines.push('');
  lines.push('> Auto-generated by `scripts/ai-smoke/run.mjs`. Do not hand-edit; re-run to refresh.');
  lines.push('');
  lines.push(`- **Run:** \`${meta.runId}\`  ·  **When:** ${isoNow()}`);
  lines.push(`- **Target:** ${meta.baseUrl}  ·  **Phase:** ${meta.phase}`);
  lines.push(`- **Domains:** ${meta.domains.join(', ')}`);
  lines.push(`- **Calls:** ${results.length}  ·  **OK:** ${passed.length}  ·  **Skipped:** ${skipped.length}  ·  **Findings:** ${findings.length}`);
  lines.push('');

  if (findings.length === 0) {
    lines.push('✅ **No findings.** Every exercised action returned an acceptable status.');
  } else {
    lines.push('## Findings by severity');
    lines.push('');
    lines.push('| Severity | Count |');
    lines.push('|----------|-------|');
    for (const sev of SEV_ORDER) if (bySeverity[sev]) lines.push(`| ${sev} | ${bySeverity[sev]} |`);
    lines.push('');
    for (const sev of SEV_ORDER) {
      const group = findings.filter((f) => f.severity === sev);
      if (!group.length) continue;
      lines.push(`### ${sev} (${group.length})`);
      lines.push('');
      lines.push('| Domain | Action | Method | Path | Status | Detail |');
      lines.push('|--------|--------|--------|------|--------|--------|');
      for (const f of group) {
        const detail = (f.body || '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').slice(0, 160);
        lines.push(`| ${f.domain} | ${f.action} | ${f.method} | \`${f.path}\` | ${f.status} | ${detail} |`);
      }
      lines.push('');
    }
  }

  lines.push('## Coverage by domain');
  lines.push('');
  lines.push('| Domain | Calls | OK | Findings | Skipped |');
  lines.push('|--------|-------|----|----------|---------|');
  for (const [d, v] of Object.entries(byDomain)) {
    lines.push(`| ${d} | ${v.total} | ${v.ok} | ${v.findings} | ${v.skipped} |`);
  }
  lines.push('');
  if (skipped.length) {
    lines.push('> Skipped samples mean the list returned no records to exercise (seed data needed), not a failure.');
    lines.push('');
  }

  fs.writeFileSync(mdPath, lines.join('\n'));

  // ----- json -----
  fs.writeFileSync(
    jsonPath,
    JSON.stringify(
      { meta: { ...meta, generatedAt: isoNow() }, summary: { total: results.length, passed: passed.length, skipped: skipped.length, findings: findings.length, bySeverity, byDomain }, findings },
      null,
      2,
    ),
  );

  return {
    total: results.length,
    passed: passed.length,
    skipped: skipped.length,
    findings: findings.length,
    bySeverity,
    mdPath,
    jsonPath,
  };
}
