#!/bin/bash
# Guard: docs/reference/auto/mcp-tools.md must reflect the current MCP tool
# registry (Ai::Tools::PlatformApiToolRegistry::TOOLS action_definitions).
# Regenerates the catalog in place, diffs the result against what was
# committed/on-disk before this check ran (ignoring the auto-generated
# timestamp line, which always changes), then restores the file to its prior
# state regardless of outcome — this is a read-only check, not a mutation.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

CATALOG="docs/reference/auto/mcp-tools.md"

before="$(mktemp)"
cp "$CATALOG" "$before"

(cd server && bundle exec rails mcp:generate_tool_catalog) >/dev/null 2>&1

if diff <(grep -v '^> Auto-generated by' "$before") <(grep -v '^> Auto-generated by' "$CATALOG") >/dev/null; then
    status=0
else
    status=1
    echo "MCP tool catalog is stale — regenerate with: cd server && bundle exec rails mcp:generate_tool_catalog" >&2
fi

cp "$before" "$CATALOG"
rm -f "$before"

exit $status
