#!/bin/bash
# Guard: docs/reference/auto/mcp-tools.md must reflect the current MCP tool
# registry (Ai::Tools::PlatformApiToolRegistry.all_tools action_definitions —
# static core TOOLS plus any extension-registered tools), as rendered by the
# PUBLIC bundle. The generation environment is pinned below; see the comment there.
# Regenerates the catalog in place, diffs the result against what was
# committed/on-disk before this check ran (ignoring the auto-generated
# timestamp line, which always changes), then restores the file to its prior
# state regardless of outcome — this is a read-only check, not a mutation.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

CATALOG="docs/reference/auto/mcp-tools.md"

before="$(mktemp)"
cp "$CATALOG" "$before"
# Restore + cleanup on ANY exit (success, failure, or interruption) — not just the
# happy path — so a failing/killed rake task never leaves the catalog dirty.
trap 'cp "$before" "$CATALOG" 2>/dev/null || true; rm -f "$before"' EXIT

# PIN THE GENERATION ENVIRONMENT. The generator reads `.all_tools`
# (= `TOOLS.merge(extension_tools)`), so its output now depends on which extension
# engines the booting bundle loads: the maintainer bundle
# (`BUNDLE_GEMFILE=Gemfile.private`) sets POWERNODE_INCLUDE_PRIVATE_EXTENSIONS=1 and
# POWERNODE_DEPLOYED=1 loads every extension present on disk, and either way engines
# register extra actions through the `register_extension_tools` seam. The TRACKED
# artifact is defined as the PUBLIC-bundle rendering (docs/reference/auto/mcp-tools.md
# is committed and ships to the public mirror), so this check pins that environment
# instead of inheriting the caller's shell: the gate behaves identically under both
# bundles, and it fails loudly if a catalog regenerated in private mode is ever
# committed. MCP_TOOL_CATALOG_OUTPUT is cleared for a different reason — it is the
# generator's spec-only output override; if it leaked in from the environment the rake
# would write somewhere else and this check would diff the catalog against its own
# untouched snapshot and report PASS having verified nothing.
(cd server && env -u BUNDLE_GEMFILE -u MCP_TOOL_CATALOG_OUTPUT \
    POWERNODE_INCLUDE_PRIVATE_EXTENSIONS=0 POWERNODE_DEPLOYED=0 \
    bundle exec rails mcp:generate_tool_catalog) >/dev/null 2>&1

if diff <(grep -v '^> Auto-generated by' "$before") <(grep -v '^> Auto-generated by' "$CATALOG") >/dev/null; then
    status=0
else
    status=1
    echo "MCP tool catalog is stale — regenerate with the PUBLIC bundle:" >&2
    echo "  cd server && env -u BUNDLE_GEMFILE POWERNODE_INCLUDE_PRIVATE_EXTENSIONS=0 POWERNODE_DEPLOYED=0 bundle exec rails mcp:generate_tool_catalog" >&2
fi

exit $status
