#!/bin/bash
# Regenerates .claude/hooks/core-purity-baseline.txt — the grandfather list for
# gate-#9 references that already exist: core -> PUBLIC-extension references, and
# (second section below) extension -> OTHER-extension references.
#
# WHY A BASELINE EXISTS FOR PUBLIC EXTENSIONS AND NOT PRIVATE ONES
# ----------------------------------------------------------------
# A private extension is ABSENT from public clones, so a CORE file naming one is
# always a leak -> the gate blocks it outright, no baseline, no exceptions.
# (The extension -> other-extension half added later IS baselined, for public and
# private targets alike — see its own section at the bottom of this file, and note
# the two output files described below. It was turned on against pre-existing
# references and would otherwise have wedged every committer on a backlog nobody
# had triaged. Entries there are isolation DEBT, not a sanctioned form; they should
# be driven to zero.)
#
# TWO OUTPUT FILES
# ----------------
# This script writes the tracked ledger AND a gitignored sibling,
# .claude/hooks/core-purity-baseline.local.txt, and routes each entry by whether
# it names a private extension at all. The tracked file is committed to core and
# published to the PUBLIC mirror, so an entry reaching it must disclose nothing —
# the leak class gate #9 exists to prevent. BOTH HALVES of an entry disclose, and
# either alone is disqualifying:
#   <path>|<slug>
#    |      `- a PRIVATE slug names the extension outright ("...|trading")
#    `- a path inside extensions/private/ names it AND its internal layout
# An entry is public-safe only when neither half does. Routing to the local file
# is also the correct scope: a public clone has no private extensions for those
# entries to describe.
#
# A public extension is PRESENT. Core legitimately documents the seams that reach
# it ("CiRunnerLease lives in extensions/system"), hosts core subtrees that merely
# share its name (frontend/src/features/system/storage), and guards optional
# constants with `defined?(::System::X)` so core degrades gracefully when the
# extension is absent. Measured on 2026-08-12: `System::` appeared in 48 core
# files (143 lines) — 61 comment lines, 32 `defined?` guards, 14 quoted strings.
# Blocking that outright would repeat the 23-false-positive revert this hook's
# header already warns about.
#
# So public coverage = block NEW references, grandfather COMMITTED ones. The
# baseline is generated from HEAD (never the working tree) precisely so that work
# in progress cannot grandfather itself in.
#
# Shrinking this file is real core-purity debt reduction. Regenerate after any
# cleanup:  ./scripts/generate-core-purity-baseline.sh
#
# Run from the repo root.
set -uo pipefail

ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || { echo "not a git repo" >&2; exit 1; }
cd "$ROOT" || exit 1
OUT=".claude/hooks/core-purity-baseline.txt"
OUT_LOCAL=".claude/hooks/core-purity-baseline.local.txt"

# Kebab slug -> PascalCase Ruby namespace (supply-chain -> SupplyChain).
pascal() {
  local s="$1" out="" part
  IFS='-' read -ra parts <<< "$s"
  for part in "${parts[@]}"; do out+="${part^}"; done
  printf '%s' "$out"
}

{
  echo "# GENERATED by scripts/generate-core-purity-baseline.sh — do not hand-edit."
  echo "# Grandfathered core -> public-extension references present in committed HEAD,"
  echo "# plus extension -> other-extension references present in the submodule trees."
  echo "# PUBLIC-SAFE ONLY: entries naming a private extension in either half live in"
  echo "# the gitignored core-purity-baseline.local.txt beside this file."
  echo "# Format: <repo-relative-path>|<extension-slug>"
  echo "# Shrinking this list is core-purity debt reduction; regenerate after cleanup."
} > "$OUT"

shopt -s nullglob
for d in extensions/*/; do
  slug="$(basename "$d")"
  [[ "$slug" == "private" ]] && continue
  ns="$(pascal "$slug")"
  pat="(\b${ns}::)|(extensions/${slug}\b)|(@ext/${slug}/)|(@${slug}/)"

  # HEAD only. Exclude anything under extensions/ (an extension may name itself).
  # Exclude comment-only lines and `defined?` guards — those are sanctioned forms
  # the gate never blocks, so they must not consume baseline entries either.
  git grep -nE "$pat" HEAD -- '*.rb' '*.ts' '*.tsx' '*.js' '*.jsx' 2>/dev/null \
    | sed 's|^HEAD:||' \
    | grep -v '^extensions/' \
    | grep -vE ':[0-9]+: *(#|//|\*)' \
    | grep -v 'defined?' \
    | cut -d: -f1 | sort -u \
    | while IFS= read -r f; do [[ -n "$f" ]] && echo "${f}|${slug}"; done
done >> "$OUT"
shopt -u nullglob

# --- EXTENSION -> OTHER-EXTENSION half ----------------------------------------
# Gate #9 also covers one extension naming ANOTHER (see
# scripts/checks/extension-cross-reference-check.sh). Those references are
# enumerated by the very check the hook and the scan run — one definition of the
# rule, not three — then split between the two ledgers by path (see TWO OUTPUT
# FILES above).
#
# DELIBERATE DEVIATION from the HEAD-only rule above: extension content lives in
# SUBMODULES, which the parent repo's `git grep HEAD` cannot see at all. The check
# therefore reads the extension working trees (i.e. whatever commit each submodule
# pointer currently has checked out). Uncommitted work inside a submodule can thus
# grandfather itself here — regenerate from a clean submodule tree, and treat a
# diff to this section as reviewable in its own right.
{
  echo "# GENERATED by scripts/generate-core-purity-baseline.sh — do not hand-edit."
  echo "# GITIGNORED, maintainer-local: every entry in which EITHER half names a private"
  echo "# extension — a path inside extensions/private/, or a private slug after the |."
  echo "# They must never reach the tracked baseline, which is published to the PUBLIC"
  echo "# mirror, where either half would disclose the extension."
  echo "# Format: <repo-relative-path>|<extension-slug>"
} > "$OUT_LOCAL"

# Private slugs, derived from disk — never hardcoded (this script is core).
shopt -s nullglob
priv_slugs=()
for d in extensions/private/*/; do priv_slugs+=("$(basename "$d")"); done
shopt -u nullglob

if [[ -r scripts/checks/extension-cross-reference-check.sh ]]; then
  # One enumeration, split by the ledger each entry belongs in. An entry goes to
  # the gitignored file if EITHER half names a private extension (see TWO OUTPUT
  # FILES above); only entries where neither half does may reach the tracked one.
  EXT_CROSS_IGNORE_BASELINE=1 bash scripts/checks/extension-cross-reference-check.sh --list \
    | while IFS= read -r line; do
        [[ -n "$line" ]] || continue
        dest="$OUT"
        case "$line" in extensions/private/*) dest="$OUT_LOCAL" ;; esac
        entry_slug="${line##*|}"
        for ps in "${priv_slugs[@]}"; do
          [[ "$entry_slug" == "$ps" ]] && { dest="$OUT_LOCAL"; break; }
        done
        echo "$line" >> "$dest"
      done
fi

n=$(grep -cv '^#' "$OUT" 2>/dev/null || echo 0)
n_local=$(grep -cv '^#' "$OUT_LOCAL" 2>/dev/null || echo 0)
echo "wrote $OUT ($n grandfathered entries)"
echo "wrote $OUT_LOCAL ($n_local maintainer-local entries, gitignored)"
