#!/bin/bash
# Regenerates .claude/hooks/core-purity-baseline.txt — the grandfather list for
# core -> PUBLIC-extension references that already exist in committed history.
#
# WHY A BASELINE EXISTS FOR PUBLIC EXTENSIONS AND NOT PRIVATE ONES
# ----------------------------------------------------------------
# A private extension is ABSENT from public clones, so a core file naming one is
# always a leak -> the gate blocks it outright, no baseline, no exceptions.
#
# A public extension is PRESENT. Core legitimately documents the seams that reach
# it ("CiRunnerLease lives in extensions/system"), hosts core subtrees that merely
# share its name (frontend/src/features/system/storage), and guards optional
# constants with `defined?(::System::X)` so core degrades gracefully when the
# extension is absent. Measured on 2026-08-12: `System::` appeared in 48 core
# files (143 lines) — 61 comment lines, 32 `defined?` guards, 14 quoted strings.
# Blocking that outright would repeat the 23-false-positive revert this hook's
# header already warns about.
#
# So public coverage = block NEW references, grandfather COMMITTED ones. The
# baseline is generated from HEAD (never the working tree) precisely so that work
# in progress cannot grandfather itself in.
#
# Shrinking this file is real core-purity debt reduction. Regenerate after any
# cleanup:  ./scripts/generate-core-purity-baseline.sh
#
# Run from the repo root.
set -uo pipefail

ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || { echo "not a git repo" >&2; exit 1; }
cd "$ROOT" || exit 1
OUT=".claude/hooks/core-purity-baseline.txt"

# Kebab slug -> PascalCase Ruby namespace (supply-chain -> SupplyChain).
pascal() {
  local s="$1" out="" part
  IFS='-' read -ra parts <<< "$s"
  for part in "${parts[@]}"; do out+="${part^}"; done
  printf '%s' "$out"
}

{
  echo "# GENERATED by scripts/generate-core-purity-baseline.sh — do not hand-edit."
  echo "# Grandfathered core -> public-extension references present in committed HEAD."
  echo "# Format: <repo-relative-path>|<extension-slug>"
  echo "# Shrinking this list is core-purity debt reduction; regenerate after cleanup."
} > "$OUT"

shopt -s nullglob
for d in extensions/*/; do
  slug="$(basename "$d")"
  [[ "$slug" == "private" ]] && continue
  ns="$(pascal "$slug")"
  pat="(\b${ns}::)|(extensions/${slug}\b)|(@ext/${slug}/)|(@${slug}/)"

  # HEAD only. Exclude anything under extensions/ (an extension may name itself).
  # Exclude comment-only lines and `defined?` guards — those are sanctioned forms
  # the gate never blocks, so they must not consume baseline entries either.
  git grep -nE "$pat" HEAD -- '*.rb' '*.ts' '*.tsx' '*.js' '*.jsx' 2>/dev/null \
    | sed 's|^HEAD:||' \
    | grep -v '^extensions/' \
    | grep -vE ':[0-9]+: *(#|//|\*)' \
    | grep -v 'defined?' \
    | cut -d: -f1 | sort -u \
    | while IFS= read -r f; do [[ -n "$f" ]] && echo "${f}|${slug}"; done
done >> "$OUT"
shopt -u nullglob

n=$(grep -cv '^#' "$OUT" 2>/dev/null || echo 0)
echo "wrote $OUT ($n grandfathered entries)"
