import React from 'react';
import type { ComponentRunbookData } from '@/shared/types/platformStatus';

// The runbook for whatever lane owns this component's signal (A9 §4.1).
//
// ── THE TWO WAYS THERE IS NO RUNBOOK ARE DIFFERENT ANSWERS ─────────────────
//
// `NoRoutedSignal` means nothing routed this component at all: there is no lane,
// so there is no document, and looking for one is a waste of an operator's time
// during an incident. `NotRegistered` / `NotDocumented` mean a lane DOES own the
// signal and its runbook is missing — a real gap, and one worth reporting.
// Collapsing the two into "no runbook" sends someone hunting for a document
// that was never supposed to exist.
//
// ── THE PATH IS NOT A LINK ─────────────────────────────────────────────────
//
// `runbook.path` is EXTENSION-RELATIVE by design: core does not know which
// checkout it belongs to. It is rendered as a locator to read, never as an href
// — a link to a filesystem path from a browser is broken by construction.

const NoRunbook: React.FC<{ reason?: string; known?: boolean }> = ({ reason, known }) => {
  if (reason === 'NoRoutedSignal') {
    return (
      <p className="text-sm text-theme-secondary">
        Nothing routes this component to a remediation lane, so there is no runbook to look for.
        This is not a missing document.
      </p>
    );
  }

  return (
    <p className="text-sm text-theme-secondary">
      A lane owns this component&apos;s signal, but no runbook is registered for it
      {known === false ? ' and the signal kind itself is unknown to the registry' : ''}. That is a
      documentation gap worth filing{reason ? ` (${reason})` : ''}.
    </p>
  );
};

export interface RunbookTabProps {
  data: ComponentRunbookData | null;
  loading: boolean;
}

export const RunbookTab: React.FC<RunbookTabProps> = ({ data, loading }) => {
  if (loading && !data) return <p className="text-sm text-theme-secondary">Loading runbook…</p>;
  if (!data) return <p className="text-sm text-theme-secondary">The runbook could not be read.</p>;

  const { runbook, signal_kind: signalKind } = data;

  return (
    <div className="flex flex-col gap-3" data-runbook-kind={runbook.kind}>
      {signalKind && (
        <p className="text-xs text-theme-tertiary">
          Signal kind <code className="text-theme-secondary">{signalKind}</code>
        </p>
      )}

      {runbook.kind === 'none' && <NoRunbook reason={runbook.reason} known={runbook.known} />}

      {runbook.kind === 'doc' && (
        <div className="rounded-md border border-theme p-3">
          <p className="text-sm text-theme-primary">{runbook.doc}</p>
          <dl className="mt-2 grid grid-cols-[minmax(0,auto)_minmax(0,1fr)] gap-x-3 gap-y-1 text-xs">
            <dt className="text-theme-tertiary">Path</dt>
            <dd
              className="font-mono text-theme-secondary break-all"
              title="Relative to the extension that registered it — core does not know which checkout that is."
            >
              {runbook.path}
            </dd>
            {runbook.anchor && (
              <>
                <dt className="text-theme-tertiary">Section</dt>
                <dd className="font-mono text-theme-secondary">{runbook.anchor}</dd>
              </>
            )}
          </dl>
        </div>
      )}

      {runbook.kind === 'generator' && (
        <div className="rounded-md border border-theme p-3">
          <p className="text-sm text-theme-primary">
            Generated by <code>{runbook.generator}</code>
          </p>
          {runbook.args && Object.keys(runbook.args).length > 0 && (
            <dl className="mt-2 grid grid-cols-[minmax(0,auto)_minmax(0,1fr)] gap-x-3 gap-y-1 text-xs">
              {Object.entries(runbook.args).map(([key, value]) => (
                <React.Fragment key={key}>
                  <dt className="font-mono text-theme-tertiary">{key}</dt>
                  <dd className="font-mono text-theme-secondary break-all">
                    {typeof value === 'object' && value !== null
                      ? JSON.stringify(value)
                      : String(value)}
                  </dd>
                </React.Fragment>
              ))}
            </dl>
          )}
        </div>
      )}
    </div>
  );
};

export default RunbookTab;
