# frozen_string_literal: true

FactoryBot.define do
  # Ai::ContentDraft — a reviewable draft of provider-ready content (D1),
  # generated by Ai::Growth::ContentDraftingService. UUIDv7 PKs are assigned
  # by the DB default.
  factory :ai_content_draft, class: "Ai::ContentDraft" do
    account
    data_source { association(:ai_data_source, account: account) }
    source_type { data_source.source_type }
    status { "draft" }
    content { "A drafted post." }
    segments { [ "A drafted post." ] }
    brand_voice { {} }
    metadata { {} }

    trait :thread do
      content { "Part one (1/2)" }
      segments { [ "Part one (1/2)", "Part two (2/2)" ] }
    end

    trait :pending_review do
      status { "pending_review" }
    end
  end
end
