import React, { useState } from 'react';
import {
  CheckCircle2,
  XCircle,
  HelpCircle,
  Clock,
  Loader2,
  AlertTriangle,
} from 'lucide-react';
import { logger } from '@/shared/utils/logger';

/**
 * Shape of a proposed change generated by `Ai::Provisioning::AdaptationProposer`.
 * Mirrors the M2 envelope returned via `platform_provisioning_adapt`.
 */
export interface AdaptationProposalProposedChange {
  summary: string;
  blast_radius: 'low' | 'med' | 'high';
  reversible: boolean;
  cost_delta_monthly_usd: number;
  resources_changed: number;
  resources_destroyed: number;
}

export interface AdaptationProposal {
  id: string;
  project_name: string;
  /** Human-readable signal description, e.g. "EU-west node CPU > 85% for 4 of last 7 days". */
  signal: string;
  /** Trigger source, e.g. "utilization sensor (auto)". */
  trigger: string;
  proposed_change: AdaptationProposalProposedChange;
  /** ISO timestamp of when the proposal was generated. Optional — if absent, no relative timestamp is rendered. */
  proposed_at?: string;
}

export interface AdaptationCardProps {
  proposal: AdaptationProposal;
  onApprove: (id: string) => Promise<void>;
  onReject: (id: string, reason?: string) => Promise<void>;
  onShowDetails: (id: string) => void;
  /**
   * Snooze callback. The plan's documented behavior: clicking "Snooze 7d" hides
   * this card for the underlying signal for **14 days** (snooze ≠ reject — the
   * sensor continues recording and may re-propose if signal strengthens).
   */
  onSnooze: (id: string, days: number) => Promise<void>;
}

const BLAST_RADIUS_STYLES: Record<
  AdaptationProposalProposedChange['blast_radius'],
  { className: string; label: string }
> = {
  low: {
    className: 'bg-theme-success-fg/10 text-theme-success-fg border border-theme-success-border/30',
    label: 'LOW',
  },
  med: {
    className: 'bg-theme-warning-fg/10 text-theme-warning-fg border border-theme-warning-border/30',
    label: 'MED',
  },
  high: {
    className: 'bg-theme-danger-fg/10 text-theme-danger-fg border border-theme-danger-border/30',
    label: 'HIGH',
  },
};

function formatRelativeTime(iso?: string): string | null {
  if (!iso) return null;
  const ts = new Date(iso).getTime();
  if (Number.isNaN(ts)) return null;
  const ms = Date.now() - ts;
  if (ms < 0) return 'just now';
  const minutes = Math.floor(ms / 60_000);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

function formatCostDelta(value: number): string {
  if (value === 0) {
    return '$0.00 / mo';
  }
  const sign = value > 0 ? '+' : '−';
  const abs = Math.abs(value).toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return `${sign}$${abs} / mo`;
}

/**
 * AdaptationCard — in-chat proposal card for adaptive evolution (M2).
 *
 * Renders a proposed system adaptation surfaced by an autonomous sensor +
 * AdaptationProposer pipeline, plus operator-facing approve/reject/snooze
 * controls and a "Why?" affordance for full reasoning.
 *
 * Theme classes: validated token catalog only — `bg-theme-info-fg/10`,
 * `bg-theme-warning-fg/10`, `bg-theme-success-fg/10`, `bg-theme-danger-fg/10`,
 * `bg-theme-interactive-primary/10`, `bg-theme-surface`,
 * `bg-theme-background-secondary`. **Never** `bg-theme-secondary` /
 * `bg-theme-tertiary` / `bg-theme-*-bg` (these don't exist).
 */
export const AdaptationCard: React.FC<AdaptationCardProps> = ({
  proposal,
  onApprove,
  onReject,
  onShowDetails,
  onSnooze,
}) => {
  const [pending, setPending] = useState<null | 'approve' | 'reject' | 'snooze'>(null);
  const blastRadius = BLAST_RADIUS_STYLES[proposal.proposed_change.blast_radius];
  const relative = formatRelativeTime(proposal.proposed_at);
  const cost = proposal.proposed_change.cost_delta_monthly_usd;
  const costClass =
    cost > 0
      ? 'text-theme-warning-fg'
      : cost < 0
        ? 'text-theme-success-fg'
        : 'text-theme-secondary';

  const run = async (kind: 'approve' | 'reject' | 'snooze', fn: () => Promise<void>) => {
    setPending(kind);
    try {
      await fn();
    } catch (err) {
      logger.error(`AdaptationCard ${kind} failed`, { proposalId: proposal.id, err });
    } finally {
      setPending(null);
    }
  };

  return (
    <div
      data-testid="adaptation-card"
      className="rounded-lg border border-theme bg-theme-surface p-4 my-3 shadow-sm"
    >
      {/* Header */}
      <div className="flex flex-wrap items-center gap-2 mb-3">
        <span
          data-testid="adaptation-header-tag"
          className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-xs font-semibold bg-theme-info-fg/10 text-theme-info-fg"
        >
          <AlertTriangle className="h-3 w-3" aria-hidden="true" />
          ADAPTATION
        </span>
        {relative && (
          <span className="inline-flex items-center gap-1 text-xs text-theme-secondary">
            <Clock className="h-3 w-3" aria-hidden="true" />
            proposed {relative}
          </span>
        )}
        <span className="text-xs text-theme-secondary">
          · for project{' '}
          <span className="font-medium text-theme-primary">{proposal.project_name}</span>
        </span>
      </div>

      {/* Signal / Trigger / Proposed change */}
      <dl className="space-y-2 text-sm">
        <div className="flex gap-2">
          <dt className="font-semibold text-theme-secondary w-24 shrink-0">Signal:</dt>
          <dd data-testid="adaptation-signal" className="text-theme-primary">
            {proposal.signal}
          </dd>
        </div>
        <div className="flex gap-2">
          <dt className="font-semibold text-theme-secondary w-24 shrink-0">Trigger:</dt>
          <dd data-testid="adaptation-trigger" className="text-theme-primary">
            {proposal.trigger}
          </dd>
        </div>
        <div className="flex gap-2">
          <dt className="font-semibold text-theme-secondary w-24 shrink-0">Proposed:</dt>
          <dd
            data-testid="adaptation-proposed-change"
            className="text-theme-primary whitespace-pre-wrap"
          >
            {proposal.proposed_change.summary}
          </dd>
        </div>
      </dl>

      {/* Meta line: blast radius + resources + cost + reversibility */}
      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mt-4 text-xs">
        <span className="text-theme-secondary">Blast radius:</span>
        <span
          data-testid="adaptation-blast-radius"
          className={`inline-flex items-center px-2 py-0.5 rounded font-semibold ${blastRadius.className}`}
        >
          {blastRadius.label}
        </span>
        <span className="text-theme-secondary">
          · {proposal.proposed_change.resources_changed} changed,{' '}
          {proposal.proposed_change.resources_destroyed} destroyed
        </span>
        <span className="text-theme-secondary">·</span>
        <span data-testid="adaptation-cost-delta" className={`font-medium ${costClass}`}>
          {formatCostDelta(cost)}
        </span>
        <span className="text-theme-secondary">·</span>
        <span
          data-testid="adaptation-reversible"
          className={
            proposal.proposed_change.reversible ? 'text-theme-success-fg' : 'text-theme-warning-fg'
          }
        >
          {proposal.proposed_change.reversible ? 'reversible' : 'irreversible'}
        </span>
      </div>

      {/* Footer */}
      <div className="flex flex-wrap items-center gap-2 mt-4 pt-3 border-t border-theme">
        <button
          type="button"
          onClick={() => run('reject', () => onReject(proposal.id))}
          disabled={pending !== null}
          data-testid="adaptation-reject"
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium bg-theme-surface border border-theme text-theme-primary hover:bg-theme-danger-fg/10 hover:border-theme-danger-border/40 hover:text-theme-danger-fg disabled:opacity-50 transition-colors"
        >
          {pending === 'reject' ? (
            <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
          ) : (
            <XCircle className="h-4 w-4" aria-hidden="true" />
          )}
          Reject
        </button>
        <button
          type="button"
          onClick={() => run('approve', () => onApprove(proposal.id))}
          disabled={pending !== null}
          data-testid="adaptation-approve"
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium bg-theme-interactive-primary text-white hover:opacity-90 disabled:opacity-50 transition-opacity"
        >
          {pending === 'approve' ? (
            <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
          ) : (
            <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
          )}
          Approve &amp; Apply
        </button>
        <button
          type="button"
          onClick={() => onShowDetails(proposal.id)}
          data-testid="adaptation-why"
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium text-theme-secondary hover:bg-theme-background-secondary transition-colors"
        >
          <HelpCircle className="h-4 w-4" aria-hidden="true" />
          Why?
        </button>
        <button
          type="button"
          onClick={() => run('snooze', () => onSnooze(proposal.id, 7))}
          disabled={pending !== null}
          data-testid="adaptation-snooze"
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium text-theme-secondary hover:bg-theme-background-secondary disabled:opacity-50 transition-colors"
        >
          {pending === 'snooze' ? (
            <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
          ) : (
            <Clock className="h-4 w-4" aria-hidden="true" />
          )}
          Snooze 7d
        </button>
      </div>
    </div>
  );
};

export default AdaptationCard;
