# frozen_string_literal: true

# Pure Markdown rendering for the system extension's skill executor catalog.
#
# Extracted from the `system:skills:generate_catalog` rake task so the
# generation — and especially TOC anchor / detail-heading slug consistency —
# is unit-testable without booting the system extension or touching the
# filesystem. The rake task collects executor descriptors (which requires the
# extension loaded) and delegates the string building here.
module SystemSkillsCatalog
  module_function

  # Mirror GitHub / Gitea (GFM) heading-anchor slugging for a heading whose
  # rendered text is +text+: downcase, drop punctuation/symbols while keeping
  # word characters (which include underscores) and hyphens, and turn spaces
  # into hyphens.
  #
  # Underscores are word characters and are preserved by GFM, so a heading
  # ``### `acme_certificate_provision` `` gets the anchor
  # `#acme_certificate_provision`. The generator previously hyphenated
  # underscores for the TOC links, producing `#acme-certificate-provision`,
  # which resolved to no heading — every catalog TOC link was broken.
  def github_slug(text)
    text.to_s
        .downcase
        .gsub(/[^\p{Word}\- ]/u, "")
        .tr(" ", "-")
  end

  # Build the full catalog Markdown from already-loaded executor descriptors.
  #
  # executors:     Array<Hash> descriptor hashes, each merged with
  #                :executor_class and :source_path (see the rake task).
  # load_failures: Array<Hash{path:, error:}> executor files that didn't load.
  # generated_at:  preformatted timestamp string for the provenance banner
  #                (nil omits the "on <time>" suffix).
  # The category bucket an executor belongs to (single source of truth for the
  # "uncategorized" default, shared by render and category_count).
  def category_key(executor)
    (executor[:category] || "uncategorized").to_s
  end

  # Number of distinct categories — used by the rake task's CLI summary so it
  # never diverges from the "across N categories" count render writes.
  def category_count(executors)
    executors.map { |e| category_key(e) }.uniq.size
  end

  def render(executors:, load_failures: [], generated_at: nil)
    by_category = executors.group_by { |e| category_key(e) }.sort

    lines = []
    lines << "# Skill Executor Catalog — System Extension (Auto-Generated)"
    lines << ""
    lines << "> Auto-generated by `rails system:skills:generate_catalog`#{generated_at ? " on #{generated_at}" : ''}."
    lines << "> Source: `descriptor()` class methods on `extensions/system/server/app/services/system/ai/skills/*_executor.rb`."
    lines << "> Do NOT edit by hand — re-run the rake task instead."
    lines << ""
    lines << "**#{executors.size} executors** across **#{by_category.size} categories**."
    if load_failures.any?
      lines << ""
      lines << "Skipped #{load_failures.size} executor file(s) that didn't load or expose a descriptor — see end of file for details."
    end
    lines << ""
    lines << "For architecture context (agent bindings, plan vs. execute pattern, invocation surfaces), see [SKILL_EXECUTORS.md](./SKILL_EXECUTORS.md)."
    lines << ""
    lines << "---"
    lines << ""

    lines << "## Table of Contents"
    lines << ""
    by_category.each do |cat, execs|
      lines << "### #{cat.titleize} (#{execs.size})"
      lines << ""
      execs.sort_by { |e| e[:name].to_s }.each do |e|
        anchor = github_slug(e[:name].to_s)
        desc   = e[:description].to_s.lines.first.to_s.chomp
        lines << "- [`#{e[:name]}`](##{anchor}) — #{desc}"
      end
      lines << ""
    end

    lines << "---"
    lines << ""

    by_category.each do |cat, execs|
      lines << "## #{cat.titleize}"
      lines << ""
      execs.sort_by { |e| e[:name].to_s }.each do |e|
        lines << "### `#{e[:name]}`"
        lines << ""
        lines << e[:description].to_s
        lines << ""
        lines << "- **Class:** `#{e[:executor_class]}`"
        lines << "- **Source:** `#{e[:source_path]}`"
        lines << "- **Category:** #{e[:category]}" if e[:category]
        lines << ""

        if e[:inputs].is_a?(Hash) && e[:inputs].any?
          lines << "**Inputs**"
          lines << ""
          lines << "| Field | Type | Required | Description |"
          lines << "|-------|------|----------|-------------|"
          e[:inputs].each do |field, spec|
            spec     = {} unless spec.is_a?(Hash)
            type     = spec[:type] || spec["type"] || "?"
            required = (spec[:required] || spec["required"]) ? "Yes" : "No"
            desc     = spec[:description] || spec["description"] || "-"
            lines << "| `#{field}` | #{type} | #{required} | #{desc} |"
          end
          lines << ""
        end

        if e[:outputs].is_a?(Hash) && e[:outputs].any?
          lines << "**Outputs**"
          lines << ""
          e[:outputs].each do |field, type|
            type_repr =
              if type.is_a?(Array)
                "array<#{type.first}>"
              else
                type.to_s
              end
            lines << "- `#{field}`: #{type_repr}"
          end
          lines << ""
        end
      end
      lines << "---"
      lines << ""
    end

    if load_failures.any?
      lines << "## Skipped executors"
      lines << ""
      lines << "These executor files did not load or did not expose a `descriptor()` class method."
      lines << "Either fix the executor or remove the file."
      lines << ""
      load_failures.each do |f|
        lines << "- `#{f[:path]}` — #{f[:error]}"
      end
      lines << ""
    end

    lines.join("\n")
  end
end
