#!/bin/bash
# Red/green test for scripts/check-claude-agents-fresh.sh's three outcomes.
#
# The check regenerates the canonical Claude Code agent skeletons into a temp
# dir and diffs them against the committed .claude/agents/powernode/. It has
# THREE outcomes, and each must be distinguishable, because "no difference"
# from an EMPTY regeneration is not freshness:
#   0  fresh         regenerated set == committed set
#   1  stale         a file differs / is missing / is extra (e.g. a renamed agent)
#   2  unverifiable  the generator SUCCEEDED and produced NO canonical agent
#                    (unseeded DB) — a WARN in pattern-validation.sh, never a PASS
#   3  broken        the generator FAILED. A crash writes zero files too, so
#                    without this it would report as the benign exit-2 WARN that
#                    is the steady state on every unseeded checkout — every
#                    generator regression invisible behind a normal-looking run.
#
# The generator is replaced through the CLAUDE_AGENTS_SYNC_CMD seam (a command
# that must write into $TARGET_DIR), and the committed dir through
# CLAUDE_AGENTS_DIR, so the outcomes are exercised without a database.
#
# Usage: bash scripts/checks/tests/check-claude-agents-fresh-test.sh
# Exits 0 if all assertions pass, 1 otherwise.
set -u

cd "$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)" || exit 1

CHECK="scripts/check-claude-agents-fresh.sh"
[[ -x "$CHECK" ]] || { echo "FAIL: $CHECK missing or not executable"; exit 1; }

fail=0
assert_exit() {
    local desc="$1" expected="$2" actual="$3"
    if [[ "$actual" -eq "$expected" ]]; then
        echo "PASS: $desc (exit $actual)"
    else
        echo "FAIL: $desc (expected exit $expected, got $actual)"
        fail=1
    fi
}

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

committed="$work/committed"
mkdir -p "$committed"
header="<!-- generated by claude:sync_agents — do not edit; regenerate instead -->"
printf -- '---\nname: fleet-autonomy\n---\n\n%s\nbody\n' "$header" > "$committed/fleet-autonomy.md"
printf -- '---\nname: sdwan-manager\n---\n\n%s\nbody\n' "$header" > "$committed/sdwan-manager.md"

# 1. fresh: the generator reproduces the committed set byte for byte.
CLAUDE_AGENTS_DIR="$committed" \
CLAUDE_AGENTS_SYNC_CMD="cp $committed/*.md \"\$TARGET_DIR\"/" \
    bash "$CHECK" >/dev/null 2>&1
assert_exit "identical regeneration is fresh" 0 $?

# 2. stale: a renamed agent (sdwan-manager -> sdwan-operator) must FAIL.
CLAUDE_AGENTS_DIR="$committed" \
CLAUDE_AGENTS_SYNC_CMD="cp $committed/fleet-autonomy.md \"\$TARGET_DIR\"/ && cp $committed/sdwan-manager.md \"\$TARGET_DIR\"/sdwan-operator.md" \
    bash "$CHECK" >/dev/null 2>&1
assert_exit "a renamed agent makes the check fail" 1 $?

# 2b. stale: a content change in one file must FAIL too.
CLAUDE_AGENTS_DIR="$committed" \
CLAUDE_AGENTS_SYNC_CMD="cp $committed/*.md \"\$TARGET_DIR\"/ && echo changed >> \"\$TARGET_DIR\"/fleet-autonomy.md" \
    bash "$CHECK" >/dev/null 2>&1
assert_exit "a changed body makes the check fail" 1 $?

# 3. unverifiable: an EMPTY regeneration (unseeded DB) is neither fresh nor stale.
CLAUDE_AGENTS_DIR="$committed" \
CLAUDE_AGENTS_SYNC_CMD="true" \
    bash "$CHECK" >/dev/null 2>&1
assert_exit "an empty regeneration is unverifiable, not a pass" 2 $?

# 5. broken generator: a NONZERO exit is exit 3, never the benign exit-2 WARN,
# even though it also produces zero files.
CLAUDE_AGENTS_DIR="$committed" \
CLAUDE_AGENTS_SYNC_CMD="echo 'rails aborted! ActiveRecord::PendingMigrationError' >&2; exit 1" \
    bash "$CHECK" >/dev/null 2>&1
assert_exit "a failing generator is broken, not unverifiable" 3 $?

# 5b. a generator that fails AFTER writing files is still broken, not a diff.
CLAUDE_AGENTS_DIR="$committed" \
CLAUDE_AGENTS_SYNC_CMD="cp $committed/*.md \"\$TARGET_DIR\"/; exit 7" \
    bash "$CHECK" >/dev/null 2>&1
assert_exit "a generator failing after writing files is still broken" 3 $?

# 5c. the broken-generator message replays the generator's own output.
out="$(CLAUDE_AGENTS_DIR="$committed" CLAUDE_AGENTS_SYNC_CMD="echo 'ZZ_MARKER_renderer_exploded' >&2; exit 1" bash "$CHECK" 2>&1)"
if grep -q "ZZ_MARKER_renderer_exploded" <<<"$out" && grep -q "not an unseeded checkout" <<<"$out"; then
    echo "PASS: broken-generator message replays the cause"
else
    echo "FAIL: broken-generator message hides the cause"; echo "$out"; fail=1
fi

# 4. the failure message documents the regen command.
out="$(CLAUDE_AGENTS_DIR="$committed" CLAUDE_AGENTS_SYNC_CMD="true; cp $committed/fleet-autonomy.md \"\$TARGET_DIR\"/" bash "$CHECK" 2>&1)"
if grep -q "claude:sync_agents" <<<"$out"; then
    echo "PASS: failure message names the regen command"
else
    echo "FAIL: failure message does not name the regen command"; echo "$out"; fail=1
fi

exit $fail
